In [46]:
import requests
import json
import sys
import pandas as pd
import csv
from  keys  import  client_id, api_key
print(sys.path)

['/Users/Mike/Flatiron_020121/yelp_phase1_project', '/opt/anaconda3/lib/python38.zip', '/opt/anaconda3/lib/python3.8', '/opt/anaconda3/lib/python3.8/lib-dynload', '', '/opt/anaconda3/lib/python3.8/site-packages', '/opt/anaconda3/lib/python3.8/site-packages/aeosa', '/opt/anaconda3/lib/python3.8/site-packages/IPython/extensions', '/Users/Mike/.ipython']

In [111]:
url =  'https://api.yelp.com/v3/businesses/search' #points to url of user's yelp developer page

headers = {
        'Authorization': 'Bearer {}'.format(api_key),
    }


# Dynamic: change term, location, and categories to pull different results from call
# * Required for defining url_params
term = 'Film Production'
location = 'Brooklyn'
categories = 'Video/Film'
spec = f'{term}_{location}_{categories}_data'

url_params = {
                "term": term.replace(' ', '+'),
                "location": location.replace(' ', '+'),
                "categories" : categories,
                "limit": 50,
                "offset": 0
            }

"""
The variables and requests below are critical, 
but have been written in to yelp_call() fn
"""
# response = requests.get(url, headers=headers, params=url_params)
# data = response.json()

In [115]:
def yelp_call(headers, url_params):
    """
    This will use the requests module to get from Yelp. 
    What is returned will be modified by our URL parameters.
    This must be called fresh with updated url_params for each call if we want to return more results.
    
    2/14 â€” defined data variable in this loop.
    """
    response = requests.get(url, headers=headers, params=url_params) # our url, header and params should be consistent, atleast with our Yelp data
    data = response.json()
    return data

In [108]:
yelp_call(headers, url_params)

{'businesses': [{'id': 'CwBYC8nVLbG7KjVU6nwR4A',
   'alias': 'dijifi-brooklyn',
   'name': 'DiJiFi',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/rzH6f1btqYDEXZtrCa_uFg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/dijifi-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 165,
   'categories': [{'alias': 'photographystores',
     'title': 'Photography Stores & Services'},
    {'alias': 'videofilmproductions', 'title': 'Video/Film Production'},
    {'alias': 'digitizingservices', 'title': 'Digitizing Services'}],
   'rating': 4.5,
   'coordinates': {'latitude': 40.7382584, 'longitude': -73.9549479},
   'transactions': [],
   'price': '$$',
   'location': {'address1': '1166 Manhattan Ave',
    'address2': 'Ste 201',
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11222',
    'country': 'US',
    'state': 'NY',
    'display_address': ['1166 Manhattan Ave',
     'Ste 201',
     'Brooklyn, NY 11222']},
   'phone': '+16465192447',
   'display_phone': '(646) 519-2447',
   'distance': 9644.708332990436},
  {'id': 'd-qaOdxKdZKe2fXEIl-i3g',
   'alias': '590films-brooklyn',
   'name': '590films',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/kTRfuDT3kgu6in2tKwm_PA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/590films-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 4,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.7280427, 'longitude': -73.9588363},
   'transactions': [],
   'location': {'address1': '42 West St',
    'address2': 'Ste 301',
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11222',
    'country': 'US',
    'state': 'NY',
    'display_address': ['42 West St', 'Ste 301', 'Brooklyn, NY 11222']},
   'phone': '+19176011911',
   'display_phone': '(917) 601-1911',
   'distance': 8577.46930920917},
  {'id': 'RJ8gQ3rFW7-iX8VA9EhDmw',
   'alias': 'shells-loft-brooklyn-brooklyn-2',
   'name': "Shell's Loft Brooklyn",
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/02nHn58jK5GquORFJ9OtUg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/shells-loft-brooklyn-brooklyn-2?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 2,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.6866128, 'longitude': -73.9616521},
   'transactions': [],
   'location': {'address1': '13 Lexington Ave',
    'address2': None,
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11238',
    'country': 'US',
    'state': 'NY',
    'display_address': ['13 Lexington Ave', 'Brooklyn, NY 11238']},
   'phone': '',
   'display_phone': '',
   'distance': 4250.413715028088},
  {'id': 'kPkv6b0jS96L0MHtQJ6O6Q',
   'alias': 'mind-of-who-productions-brooklyn',
   'name': 'Mind of Who Productions',
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/APHPC8lX8qHLBYpQMP7ojA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/mind-of-who-productions-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 2,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'},
    {'alias': 'sessionphotography', 'title': 'Session Photography'},
    {'alias': 'marketing', 'title': 'Marketing'}],
   'rating': 4.5,
   'coordinates': {'latitude': 40.691765, 'longitude': -73.939434},
   'transactions': [],
   'location': {'address1': '193 Marcus Garvey Blvd',
    'address2': None,
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11221',
    'country': 'US',
    'state': 'NY',
    'display_address': ['193 Marcus Garvey Blvd', 'Brooklyn, NY 11221']},
   'phone': '+19172506393',
   'display_phone': '(917) 250-6393',
   'distance': 4385.456637872636},
  {'id': '9uHmHMAsMiGnCulUL_8cLQ',
   'alias': 'kaleidoscope-pictures-brooklyn-4',
   'name': 'Kaleidoscope Pictures',
   'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/N0Rk2YgOFpP_KEUFaGdqhA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/kaleidoscope-pictures-brooklyn-4?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 8,
   'categories': [{'alias': 'sessionphotography',
     'title': 'Session Photography'},
    {'alias': 'eventphotography', 'title': 'Event Photography'},
    {'alias': 'videofilmproductions', 'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.6772802, 'longitude': -74.0094471},
   'transactions': [],
   'location': {'address1': '',
    'address2': '',
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11231',
    'country': 'US',
    'state': 'NY',
    'display_address': ['Brooklyn, NY 11231']},
   'phone': '+13472940461',
   'display_phone': '(347) 294-0461',
   'distance': 6530.019169574993},
  {'id': '6xZHiBQiaC9o1Jma1BSu7A',
   'alias': 'cinema-world-studios-brooklyn',
   'name': 'Cinema World Studios',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/8imIHlUxthosRWMNz2Olww/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/cinema-world-studios-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 2,
   'categories': [{'alias': 'theater', 'title': 'Performing Arts'},
    {'alias': 'videofilmproductions', 'title': 'Video/Film Production'}],
   'rating': 4.5,
   'coordinates': {'latitude': 40.735954, 'longitude': -73.950508},
   'transactions': [],
   'location': {'address1': '220 Dupont St',
    'address2': '',
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11222',
    'country': 'US',
    'state': 'NY',
    'display_address': ['220 Dupont St', 'Brooklyn, NY 11222']},
   'phone': '+17183899800',
   'display_phone': '(718) 389-9800',
   'distance': 9339.009296897631},
  {'id': 'ZjlpNq7IDej7Y2lH1Ptu9A',
   'alias': 'starr-street-media-brooklyn',
   'name': 'Starr Street Media',
   'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/EaJU5hojfcvuATeB03OSnA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/starr-street-media-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 1,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.64986, 'longitude': -73.95257},
   'transactions': [],
   'location': {'address1': '852 Rogers Ave',
    'address2': None,
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11226',
    'country': 'US',
    'state': 'NY',
    'display_address': ['852 Rogers Ave', 'Brooklyn, NY 11226']},
   'phone': '+19545345281',
   'display_phone': '(954) 534-5281',
   'distance': 1147.5972555682438},
  {'id': 'ntnuLH-tk9Qh8n895hDV9g',
   'alias': 'hit-and-run-productions-brooklyn-2',
   'name': 'Hit and Run Productions',
   'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/EmeblIbUFmnqr11XPduBmw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/hit-and-run-productions-brooklyn-2?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 4,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'},
    {'alias': 'costumes', 'title': 'Costumes'},
    {'alias': 'props', 'title': 'Props'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.7165128, 'longitude': -73.9546435},
   'transactions': [],
   'location': {'address1': '65 Roebling St',
    'address2': 'Ste 202',
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11211',
    'country': 'US',
    'state': 'NY',
    'display_address': ['65 Roebling St', 'Ste 202', 'Brooklyn, NY 11211']},
   'phone': '+17188099057',
   'display_phone': '(718) 809-9057',
   'distance': 7252.173501781825},
  {'id': 'wvWXLBTqF4JdD5_QCXiR_g',
   'alias': 'bk-actors-self-tape-brooklyn',
   'name': 'BK Actors Self-Tape',
   'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/P8xsPYlO2Bj128He_oxXPw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/bk-actors-self-tape-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 14,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'},
    {'alias': 'specialtyschools', 'title': 'Specialty Schools'},
    {'alias': 'studiotaping', 'title': 'Studio Taping'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.6985551, 'longitude': -73.9712029},
   'transactions': [],
   'location': {'address1': '141 Flushing Ave',
    'address2': 'Bldg 77 ,Ste 1336',
    'address3': 'Brooklyn Navy Yard',
    'city': 'Brooklyn',
    'zip_code': '11205',
    'country': 'US',
    'state': 'NY',
    'display_address': ['141 Flushing Ave',
     'Bldg 77 ,Ste 1336',
     'Brooklyn Navy Yard',
     'Brooklyn, NY 11205']},
   'phone': '+16466848783',
   'display_phone': '(646) 684-8783',
   'distance': 5799.12132624071},
  {'id': 'dQeD7LOvK4owK-8ysfu9gQ',
   'alias': 'bizvidmedia-productions-new-york',
   'name': 'Bizvidmedia Productions',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/CtmtV1lycc7GW1etLph5Bw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/bizvidmedia-productions-new-york?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 5,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.70479, 'longitude': -74.00726},
   'transactions': [],
   'location': {'address1': '99 Wallstreet',
    'address2': None,
    'address3': '',
    'city': 'New York',
    'zip_code': '10005',
    'country': 'US',
    'state': 'NY',
    'display_address': ['99 Wallstreet', 'New York, NY 10005']},
   'phone': '+16039180366',
   'display_phone': '(603) 918-0366',
   'distance': 8176.437971004501},
  {'id': '8v0pPzCHOgJKGmydp2_xCA',
   'alias': 'indigo-productions-new-york',
   'name': 'Indigo Productions',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/UKx8huUwBenfI9BXWhDxSw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/indigo-productions-new-york?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 5,
   'categories': [{'alias': 'videographers', 'title': 'Videographers'},
    {'alias': 'videofilmproductions', 'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.7908706665039,
    'longitude': -73.9751968383789},
   'transactions': [],
   'location': {'address1': '250 W 90th St',
    'address2': '',
    'address3': '',
    'city': 'New York',
    'zip_code': '10024',
    'country': 'US',
    'state': 'NY',
    'display_address': ['250 W 90th St', 'New York, NY 10024']},
   'phone': '+12127655224',
   'display_phone': '(212) 765-5224',
   'distance': 15691.3636537472},
  {'id': 'Y_omLPmjGaeDVEvfMgn67w',
   'alias': 'silentface-brooklyn',
   'name': 'Silentface',
   'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/wJD7HE7S5KFXg1GRGJ5Qmg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/silentface-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 1,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.69445, 'longitude': -73.92036},
   'transactions': [],
   'location': {'address1': '86 Menahan St',
    'address2': 'Ste 2L',
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11221',
    'country': 'US',
    'state': 'NY',
    'display_address': ['86 Menahan St', 'Ste 2L', 'Brooklyn, NY 11221']},
   'phone': '+13473917665',
   'display_phone': '(347) 391-7665',
   'distance': 4951.91438836514},
  {'id': 'fEtC46_MLieftlPK-0G3Gw',
   'alias': 'killer-combo-studios-brooklyn',
   'name': 'Killer Combo Studios',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/5485LNWZZoORR0xRI1S3zw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/killer-combo-studios-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 7,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'},
    {'alias': 'sessionphotography', 'title': 'Session Photography'},
    {'alias': 'eventphotography', 'title': 'Event Photography'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.678534, 'longitude': -73.958435},
   'transactions': [],
   'location': {'address1': '641 Classon Ave',
    'address2': '',
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11238',
    'country': 'US',
    'state': 'NY',
    'display_address': ['641 Classon Ave', 'Brooklyn, NY 11238']},
   'phone': '+15108603933',
   'display_phone': '(510) 860-3933',
   'distance': 3328.3426280951708},
  {'id': '2eJfWKhPxnAwqylZN7S-4g',
   'alias': 'iris-cinematics-jersey-city',
   'name': 'Iris Cinematics',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/ltLUr4gChwWmCpC62ib1dA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/iris-cinematics-jersey-city?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 1,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.7199096679688,
    'longitude': -74.0432891845703},
   'transactions': [],
   'location': {'address1': '121 Newark Ave',
    'address2': 'Ste 506',
    'address3': '',
    'city': 'Jersey City',
    'zip_code': '07302',
    'country': 'US',
    'state': 'NJ',
    'display_address': ['121 Newark Ave', 'Ste 506', 'Jersey City, NJ 07302']},
   'phone': '+12019782191',
   'display_phone': '(201) 978-2191',
   'distance': 11543.71921473275},
  {'id': 'nLDKxf054v1bF6N6YYK57w',
   'alias': 'amy-lawday-films-brooklyn',
   'name': 'Amy Lawday Films',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/IcT6RQDfhyRrfevxMYjtFw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/amy-lawday-films-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 1,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.67772, 'longitude': -73.96312},
   'transactions': [],
   'location': {'address1': '',
    'address2': '',
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11238',
    'country': 'US',
    'state': 'NY',
    'display_address': ['Brooklyn, NY 11238']},
   'phone': '+16463454060',
   'display_phone': '(646) 345-4060',
   'distance': 3687.827150141654},
  {'id': '4Xy1UH_wAaHQ2GQPiq8d2A',
   'alias': 'an-olivetree-production-new-york',
   'name': 'An Olivetree Production',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/jWcy-XHNhij4YMm1ycNdug/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/an-olivetree-production-new-york?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 1,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'},
    {'alias': 'videographers', 'title': 'Videographers'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.7061738002948,
    'longitude': -73.9202935099089},
   'transactions': [],
   'location': {'address1': '1350 Willoughby Ave',
    'address2': '',
    'address3': '',
    'city': 'New York',
    'zip_code': '11237',
    'country': 'US',
    'state': 'NY',
    'display_address': ['1350 Willoughby Ave', 'New York, NY 11237']},
   'phone': '+15164244412',
   'display_phone': '(516) 424-4412',
   'distance': 6199.296608655763},
  {'id': 'vWjWvJFG64W9Mti7EvmgYQ',
   'alias': 'steiner-studios-brooklyn-2',
   'name': 'Steiner Studios',
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/5lBwkiC614K49agW0-OLXQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/steiner-studios-brooklyn-2?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 7,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 4.5,
   'coordinates': {'latitude': 40.6983157794782,
    'longitude': -73.967696428299},
   'transactions': [],
   'location': {'address1': '15 Washington Ave',
    'address2': '',
    'address3': '',
    'city': 'Brooklyn',
    'zip_code': '11205',
    'country': 'US',
    'state': 'NY',
    'display_address': ['15 Washington Ave', 'Brooklyn, NY 11205']},
   'phone': '+17188581600',
   'display_phone': '(718) 858-1600',
   'distance': 5644.141729496968},
  {'id': 'CjI40qw7Djs13FhjfyM6Ig',
   'alias': 'ground-glass-motion-picture-company-new-york',
   'name': 'Ground Glass Motion Picture Company',
   'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/K_BAt-gUIBr0PW9EPoo2zA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/ground-glass-motion-picture-company-new-york?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 1,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.7221489, 'longitude': -73.9923325},
   'transactions': [],
   'location': {'address1': '195 Christie St',
    'address2': '',
    'address3': '',
    'city': 'New York',
    'zip_code': '10002',
    'country': 'US',
    'state': 'NY',
    'display_address': ['195 Christie St', 'New York, NY 10002']},
   'phone': '',
   'display_phone': '',
   'distance': 8938.820707989016},
  {'id': 'vlf3FBanE3sWdtlogKBHXQ',
   'alias': 'vengo-films-brooklyn',
   'name': 'Vengo Films',
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/Suk_8LzRBu5bJnCvDEHGCg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/vengo-films-brooklyn?adjust_creative=vGqQbkXzrgSl7z2qib6lAg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=vGqQbkXzrgSl7z2qib6lAg',
   'review_count': 1,
   'categories': [{'alias': 'videofilmproductions',
     'title': 'Video/Film Production'}],
   'rating': 5.0,
   'coordinates': {'latitude': 40.620018, 'longitude': -74.0292025},
   'transactions': [],
   'location': {'address1': '8913 4th Ave',
    'address2': 'Ste 5837',
    'address3': None,
    'city': 'Brooklyn',
    'zip_code': '11209',
    'country': 'US',
    'state': 'NY',
    'display_address': ['8913 4th Ave', 'Ste 5837', 'Brooklyn, NY 11209']},
   'phone': '+13473319022',
   'display_phone': '(347) 331-9022',
   'distance': 8389.23207785749},
  {'id': 'FOVaV6u49Hb3VEncHJ5eVg',
   'alias': 'urban-myth-studio-brooklyn',

In [117]:
# data['total']
yelp_call(headers, url_params)['total']

298

In [50]:
def parse_data(list_of_data):
    """
    Input data['businesses'] to return a list of tuples,
    with each tuple containing individual business name, address, and other items
    """
    businesses = []
    for business in list_of_data:
        biz_price = None
        if 'price' not in business.keys():
            biz_price = None
        else:
            biz_price = len(business['price'])
        biz_tuple = (business['name'],
                     business['location']['display_address'],
                     business['location']['city'],
                     business['rating'],
                     business['review_count'],
                     business['coordinates'],
                     biz_price)
        businesses.append(biz_tuple)
    return businesses

In [344]:
"""
JAKE I FUCKING DID IT

WE DON'T EVEN GET AN ERROR MESSAGE ANYMORE
"""
csv_filepath = f'database/{term}_{location}_database.csv'

def call_1000(csv_filepath):
    url_params['offset'] = 0
    results = yelp_call(headers, url_params)
    parsed = parse_data(results['businesses']) # list of businesses in tuples
    num = results['total']
    biz_list = []
    while url_params['offset'] < 1000 and len(biz_list) < num:
        for biz in parsed:
            biz_list.append(biz)
        url_params['offset'] += 50
        results = yelp_call(headers, url_params)
        if num >= len(biz_list):
            if 'businesses' not in results:
                break
            else:
                parsed = parse_data(results['businesses']) # list of businesses in tuples
        elif len(biz_list) <= 950:
            continue
        else:
            break
    df = pd.DataFrame(biz_list, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
    with open(csv_filepath, "a") as f: #'x' creates and writes to csv
        read_file = csv.writer(f)
        df.to_csv(csv_filepath, mode = "a", index = False)
    print('CSV file written to {csv_filepath}.')
    return df

In [345]:
call_1000(csv_filepath)

,Name,Address,City,Rating,Review Count,Coordinates,Price
0,DiJiFi,"[1166 Manhattan Ave, Ste 201, Brooklyn, NY 11222]",Brooklyn,4.5,165,"{'latitude': 40.7382584, 'longitude': -73.9549...",2.0
1,590films,"[42 West St, Ste 301, Brooklyn, NY 11222]",Brooklyn,5.0,4,"{'latitude': 40.7280427, 'longitude': -73.9588...",NaN
2,Kaleidoscope Pictures,"[Brooklyn, NY 11231]",Brooklyn,5.0,8,"{'latitude': 40.6772802, 'longitude': -74.0094...",NaN
3,Shell's Loft Brooklyn,"[13 Lexington Ave, Brooklyn, NY 11238]",Brooklyn,5.0,2,"{'latitude': 40.6866128, 'longitude': -73.9616...",NaN
4,Mind of Who Productions,"[193 Marcus Garvey Blvd, Brooklyn, NY 11221]",Brooklyn,4.5,2,"{'latitude': 40.691765, 'longitude': -73.939434}",NaN
...,...,...,...,...,...,...,...
291,Secret Fire Media,"[Wappingers Falls, NY 12590]",Wappingers Falls,4.0,10,"{'latitude': 41.59696, 'longitude': -73.91325}",NaN
292,Cinescope,"[5 S Main St, Doylestown, PA 18901]",Doylestown,5.0,3,"{'latitude': 40.309828966856, 'longitude': -75...",NaN
293,Jordan Green Productions,"[3502 Leavenworth St, Omaha, NE 68105]",Omaha,1.0,1,"{'latitude': 41.252651, 'longitude': -95.964111}",NaN
294,BeauMonde Originals,"[3128 N 35th St, Philadelphia, PA 19132]",Philadelphia,5.0,2,"{'latitude': 40.00559, 'longitude': -75.18678}",NaN
295,Kiss the Bride Films,"[San Francisco, CA 94103]",San Francisco,5.0,14,"{'latitude': 37.7744789123535, 'longitude': -1...",NaN

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

# Tests below 
### (first cell through yelp call must be run before these)

In [73]:
parsed = parse_data(data['businesses'])
parsed

[('DiJiFi',
  ['1166 Manhattan Ave', 'Ste 201', 'Brooklyn, NY 11222'],
  'Brooklyn',
  4.5,
  165,
  {'latitude': 40.7382584, 'longitude': -73.9549479},
  2),
 ('590films',
  ['42 West St', 'Ste 301', 'Brooklyn, NY 11222'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.7280427, 'longitude': -73.9588363},
  None),
 ("Shell's Loft Brooklyn",
  ['13 Lexington Ave', 'Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  2,
  {'latitude': 40.6866128, 'longitude': -73.9616521},
  None),
 ('Mind of Who Productions',
  ['193 Marcus Garvey Blvd', 'Brooklyn, NY 11221'],
  'Brooklyn',
  4.5,
  2,
  {'latitude': 40.691765, 'longitude': -73.939434},
  None),
 ('Kaleidoscope Pictures',
  ['Brooklyn, NY 11231'],
  'Brooklyn',
  5.0,
  8,
  {'latitude': 40.6772802, 'longitude': -74.0094471},
  None),
 ('Cinema World Studios',
  ['220 Dupont St', 'Brooklyn, NY 11222'],
  'Brooklyn',
  4.5,
  2,
  {'latitude': 40.735954, 'longitude': -73.950508},
  None),
 ('Starr Street Media',
  ['852 Rogers Ave', 'Brooklyn, NY 11226'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.64986, 'longitude': -73.95257},
  None),
 ('Hit and Run Productions',
  ['65 Roebling St', 'Ste 202', 'Brooklyn, NY 11211'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.7165128, 'longitude': -73.9546435},
  None),
 ('BK Actors Self-Tape',
  ['141 Flushing Ave',
   'Bldg 77 ,Ste 1336',
   'Brooklyn Navy Yard',
   'Brooklyn, NY 11205'],
  'Brooklyn',
  5.0,
  14,
  {'latitude': 40.6985551, 'longitude': -73.9712029},
  None),
 ('Bizvidmedia Productions',
  ['99 Wallstreet', 'New York, NY 10005'],
  'New York',
  5.0,
  5,
  {'latitude': 40.70479, 'longitude': -74.00726},
  None),
 ('Indigo Productions',
  ['250 W 90th St', 'New York, NY 10024'],
  'New York',
  5.0,
  5,
  {'latitude': 40.7908706665039, 'longitude': -73.9751968383789},
  None),
 ('Silentface',
  ['86 Menahan St', 'Ste 2L', 'Brooklyn, NY 11221'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.69445, 'longitude': -73.92036},
  None),
 ('Killer Combo Studios',
  ['641 Classon Ave', 'Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  7,
  {'latitude': 40.678534, 'longitude': -73.958435},
  None),
 ('Iris Cinematics',
  ['121 Newark Ave', 'Ste 506', 'Jersey City, NJ 07302'],
  'Jersey City',
  5.0,
  1,
  {'latitude': 40.7199096679688, 'longitude': -74.0432891845703},
  None),
 ('Amy Lawday Films',
  ['Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.67772, 'longitude': -73.96312},
  None),
 ('An Olivetree Production',
  ['1350 Willoughby Ave', 'New York, NY 11237'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7061738002948, 'longitude': -73.9202935099089},
  None),
 ('Steiner Studios',
  ['15 Washington Ave', 'Brooklyn, NY 11205'],
  'Brooklyn',
  4.5,
  7,
  {'latitude': 40.6983157794782, 'longitude': -73.967696428299},
  None),
 ('Ground Glass Motion Picture Company',
  ['195 Christie St', 'New York, NY 10002'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7221489, 'longitude': -73.9923325},
  None),
 ('Vengo Films',
  ['8913 4th Ave', 'Ste 5837', 'Brooklyn, NY 11209'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.620018, 'longitude': -74.0292025},
  None),
 ('Urban Myth Studio',
  ['505 Johnson Ave', 'Brooklyn, NY 11237'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.708663918903, 'longitude': -73.926939086334},
  None),
 ('Automatic Studios',
  ['52 Bridge St', 'Brooklyn, NY 11201'],
  'Brooklyn',
  4.0,
  7,
  {'latitude': 40.703069, 'longitude': -73.98468},
  None),
 ('The Cubed Effect',
  ['New York, NY 11201'],
  'New York',
  5.0,
  4,
  {'latitude': 40.69347, 'longitude': -73.99052},
  None),
 ('Gee Media',
  ['Brooklyn, NY 11225'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.66363, 'longitude': -73.95541},
  None),
 ('Miller/Datri Entertainment',
  ['600 Fifth Ave', 'Fl 2', 'New York, NY 10020'],
  'New York',
  5.0,
  4,
  {'latitude': 40.758596, 'longitude': -73.9784575},
  None),
 ('Film Trade',
  ['86 Verona St', 'New York, NY 11231'],
  'New York',
  5.0,
  1,
  {'latitude': 40.6796212181687, 'longitude': -74.0091629592533},
  None),
 ('Hello World Communications',
  ['118 W 22nd St', 'Fl 2', 'New York, NY 10011'],
  'New York',
  5.0,
  42,
  {'latitude': 40.7425398, 'longitude': -73.9945521},
  None),
 ('RUX Media',
  ['50 Harrison St', 'Hoboken, NJ 07030'],
  'Hoboken',
  5.0,
  1,
  {'latitude': 40.7372343, 'longitude': -74.042797},
  None),
 ('And/With Creative',
  ['102 Bay Ridge Ave', 'Ste 2F', 'Brooklyn, NY 11220'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.63741, 'longitude': -74.03218},
  None),
 ('New York Film Shop',
  ['437 Washington St', 'New York, NY 10013'],
  'New York',
  5.0,
  3,
  {'latitude': 40.7232895, 'longitude': -74.0101166},
  None),
 ('GUM Studios',
  ['4508 2nd Ave', 'Brooklyn, NY 11232'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.65181, 'longitude': -74.0143},
  None),
 ('Cage Free Productions',
  ['15 Hawthorne St', 'Ste 3B', 'Brooklyn, NY 11225'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.657474, 'longitude': -73.959732},
  None),
 ('Starr Street Studios',
  ['207-A Starr St', 'Ste 3-1', 'Brooklyn, NY 11237'],
  'Brooklyn',
  5.0,
  8,
  {'latitude': 40.705122, 'longitude': -73.923457},
  None),
 ('The Edit Center',
  ['168 7th St', 'Ste 314', 'Brooklyn, NY 11215'],
  'Brooklyn',
  5.0,
  6,
  {'latitude': 40.6728208, 'longitude': -73.9909742},
  None),
 ('Muve Media',
  ['36 Waverly Ave', 'Brooklyn, NY 11205'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.696788, 'longitude': -73.968833},
  None),
 ('MRD Productions',
  ['500 W 30th St', 'New York, NY 10001'],
  'New York',
  5.0,
  1,
  {'latitude': 40.75194, 'longitude': -74.00156},
  None),
 ('V-Productions',
  ['469 7th Ave', 'New York, NY 10018'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7519226, 'longitude': -73.9894887},
  None),
 ('Deverge Studio',
  ['150 W 28th St', 'Ste 600', 'New York, NY 10001'],
  'New York',
  5.0,
  5,
  {'latitude': 40.74676, 'longitude': -73.99282},
  None),
 ('Eastern Effects',
  ['99 9th St', 'Brooklyn, NY 11215'],
  'Brooklyn',
  4.5,
  3,
  {'latitude': 40.6734029529525, 'longitude': -73.9946415645175},
  None),
 ('The Self Tape Space',
  ['W 118th St & Manhattan Ave', 'New York, NY 10026'],
  'New York',
  5.0,
  13,
  {'latitude': 40.806343, 'longitude': -73.955873},
  None),
 ('Tom Ragan Films',
  ['Brooklyn, NY 11215'],
  'Brooklyn',
  5.0,
  2,
  {'latitude': 40.66889, 'longitude': -73.9819},
  None),
 ('Fine Art Productions',
  ['1655 Oak Tree Rd', 'Ste 270', 'Edison, NJ 08820'],
  'Edison',
  4.5,
  19,
  {'latitude': 40.5709695115082, 'longitude': -74.340228068968},
  None),
 ('Hello Super Studios',
  ['Brooklyn, NY 11206'],
  'Brooklyn',
  5.0,
  9,
  {'latitude': 40.7038917541504, 'longitude': -73.9447479248047},
  None),
 ('AbelCine',
  ['Industry City', '88 35th St, Fl 4', 'Brooklyn, NY 11232'],
  'Brooklyn',
  3.5,
  9,
  {'latitude': 40.6564111, 'longitude': -74.0067047},
  4),
 ('Jersey Filmmaker',
  ['Jersey City, NJ 07302'],
  'Jersey City',
  5.0,
  1,
  {'latitude': 40.7218017578125, 'longitude': -74.0449295043945},
  None),
 ('Latour de Force Productions',
  ['New York, NY 10019'],
  'New York',
  5.0,
  7,
  {'latitude': 40.7645378112793, 'longitude': -73.9842376708984},
  None),
 ('Brain Fry Productions',
  ['2853 Steinway St', '2F', 'Astoria, NY 11103'],
  'Astoria',
  5.0,
  2,
  {'latitude': 40.630508, 'longitude': -74.028456},
  None),
 ('Silvercup Studios',
  ['42-22 22nd St', 'Long Island City, NY 11101'],
  'Long Island City',
  4.5,
  12,
  {'latitude': 40.751331, 'longitude': -73.943515},
  None),
 ('YouTube Space',
  ['75 9th Ave', 'New York, NY 10011'],
  'New York',
  5.0,
  6,
  {'latitude': 40.742581, 'longitude': -74.005434},
  None),
 ('Sun Production',
  ['36-06 30th St', 'C7', 'Astoria, NY 11106'],
  'Astoria',
  5.0,
  1,
  {'latitude': 40.756815, 'longitude': -73.930988},
  None),
 ('Broadway Stages',
  ['359 Kingsland Ave', 'Greenpoint, NY 11222'],
  'Greenpoint',
  4.0,
  1,
  {'latitude': 40.7289565103425, 'longitude': -73.9424950629473},
  None)]

In [74]:
pd.DataFrame(parsed, columns =['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])

,Name,Address,City,Rating,Review Count,Coordinates,Price
0,DiJiFi,"[1166 Manhattan Ave, Ste 201, Brooklyn, NY 11222]",Brooklyn,4.5,165,"{'latitude': 40.7382584, 'longitude': -73.9549...",2.0
1,590films,"[42 West St, Ste 301, Brooklyn, NY 11222]",Brooklyn,5.0,4,"{'latitude': 40.7280427, 'longitude': -73.9588...",NaN
2,Shell's Loft Brooklyn,"[13 Lexington Ave, Brooklyn, NY 11238]",Brooklyn,5.0,2,"{'latitude': 40.6866128, 'longitude': -73.9616...",NaN
3,Mind of Who Productions,"[193 Marcus Garvey Blvd, Brooklyn, NY 11221]",Brooklyn,4.5,2,"{'latitude': 40.691765, 'longitude': -73.939434}",NaN
4,Kaleidoscope Pictures,"[Brooklyn, NY 11231]",Brooklyn,5.0,8,"{'latitude': 40.6772802, 'longitude': -74.0094...",NaN
5,Cinema World Studios,"[220 Dupont St, Brooklyn, NY 11222]",Brooklyn,4.5,2,"{'latitude': 40.735954, 'longitude': -73.950508}",NaN
6,Starr Street Media,"[852 Rogers Ave, Brooklyn, NY 11226]",Brooklyn,5.0,1,"{'latitude': 40.64986, 'longitude': -73.95257}",NaN
7,Hit and Run Productions,"[65 Roebling St, Ste 202, Brooklyn, NY 11211]",Brooklyn,5.0,4,"{'latitude': 40.7165128, 'longitude': -73.9546...",NaN
8,BK Actors Self-Tape,"[141 Flushing Ave, Bldg 77 ,Ste 1336, Brooklyn...",Brooklyn,5.0,14,"{'latitude': 40.6985551, 'longitude': -73.9712...",NaN
9,Bizvidmedia Productions,"[99 Wallstreet, New York, NY 10005]",New York,5.0,5,"{'latitude': 40.70479, 'longitude': -74.00726}",NaN
10,Indigo Productions,"[250 W 90th St, New York, NY 10024]",New York,5.0,5,"{'latitude': 40.7908706665039, 'longitude': -7...",NaN
11,Silentface,"[86 Menahan St, Ste 2L, Brooklyn, NY 11221]",Brooklyn,5.0,1,"{'latitude': 40.69445, 'longitude': -73.92036}",NaN
12,Killer Combo Studios,"[641 Classon Ave, Brooklyn, NY 11238]",Brooklyn,5.0,7,"{'latitude': 40.678534, 'longitude': -73.958435}",NaN
13,Iris Cinematics,"[121 Newark Ave, Ste 506, Jersey City, NJ 07302]",Jersey City,5.0,1,"{'latitude': 40.7199096679688, 'longitude': -7...",NaN
14,Amy Lawday Films,"[Brooklyn, NY 11238]",Brooklyn,5.0,1,"{'latitude': 40.67772, 'longitude': -73.96312}",NaN
15,An Olivetree Production,"[1350 Willoughby Ave, New York, NY 11237]",New York,5.0,1,"{'latitude': 40.7061738002948, 'longitude': -7...",NaN
16,Steiner Studios,"[15 Washington Ave, Brooklyn, NY 11205]",Brooklyn,4.5,7,"{'latitude': 40.6983157794782, 'longitude': -7...",NaN
17,Ground Glass Motion Picture Company,"[195 Christie St, New York, NY 10002]",New York,5.0,1,"{'latitude': 40.7221489, 'longitude': -73.9923...",NaN
18,Vengo Films,"[8913 4th Ave, Ste 5837, Brooklyn, NY 11209]",Brooklyn,5.0,1,"{'latitude': 40.620018, 'longitude': -74.0292025}",NaN
19,Urban Myth Studio,"[505 Johnson Ave, Brooklyn, NY 11237]",Brooklyn,5.0,4,"{'latitude': 40.708663918903, 'longitude': -73...",NaN
20,Automatic Studios,"[52 Bridge St, Brooklyn, NY 11201]",Brooklyn,4.0,7,"{'latitude': 40.703069, 'longitude': -73.98468}",NaN
21,The Cubed Effect,"[New York, NY 11201]",New York,5.0,4,"{'latitude': 40.69347, 'longitude': -73.99052}",NaN
22,Gee Media,"[Brooklyn, NY 11225]",Brooklyn,5.0,4,"{'latitude': 40.66363, 'longitude': -73.95541}",NaN
23,Miller/Datri Entertainment,"[600 Fifth Ave, Fl 2, New York, NY 10020]",New York,5.0,4,"{'latitude': 40.758596, 'longitude': -73.9784575}",NaN
24,Film Trade,"[86 Verona St, New York, NY 11231]",New York,5.0,1,"{'latitude': 40.6796212181687, 'longitude': -7...",NaN
25,Hello World Communications,"[118 W 22nd St, Fl 2, New York, NY 10011]",New York,5.0,42,"{'latitude': 40.7425398, 'longitude': -73.9945...",NaN
26,RUX Media,"[50 Harrison St, Hoboken, NJ 07030]",Hoboken,5.0,1,"{'latitude': 40.7372343, 'longitude': -74.042797}",NaN
27,And/With Creative,"[102 Bay Ridge Ave, Ste 2F, Brooklyn, NY 11220]",Brooklyn,5.0,1,"{'latitude': 40.63741, 'longitude': -74.03218}",NaN
28,New York Film Shop,"[437 Washington St, New York, NY 10013]",New York,5.0,3,"{'latitude': 40.7232895, 'longitude': -74.0101...",NaN
29,GUM Studios,"[4508 2nd Ave, Brooklyn, NY 11232]",Brooklyn,5.0,1,"{'latitude': 40.65181, 'longitude': -74.0143}",NaN
30,Cage Free Productions,"[15 Hawthorne St, Ste 3B, Brooklyn, NY 11225]",Brooklyn,5.0,1,"{'latitude': 40.657474, 'longitude': -73.959732}",NaN
31,Starr Street Studios,"[207-A Starr St, Ste 3-1, Brooklyn, NY 11237]",Brooklyn,5.0,8,"{'latitude': 40.705122, 'longitude': -73.923457}",NaN
32,The Edit Center,"[168 7th St, Ste 314, Brooklyn, NY 11215]",Brooklyn,5.0,6,"{'latitude': 40.6728208, 'longitude': -73.9909...",NaN
33,Muve Media,"[36 Waverly Ave, Brooklyn, NY 11205]",Brooklyn,5.0,1,"{'latitude': 40.696788, 'longitude': -73.968833}",NaN
34,MRD Productions,"[500 W 30th St, New York, NY 10001]",New York,5.0,1,"{'latitude': 40.75194, 'longitude': -74.00156}",NaN
35,V-Productions,"[469 7th Ave, New York, NY 10018]",New York,5.0,1,"{'latitude': 40.7519226, 'longitude': -73.9894...",NaN
36,Deverge Studio,"[150 W 28th St, Ste 600, New York, NY 10001]",New York,5.0,5,"{'latitude': 40.74676, 'longitude': -73.99282}",NaN
37,Eastern Effects,"[99 9th St, Brooklyn, NY 11215]",Brooklyn,4.5,3,"{'latitude': 40.6734029529525, 'longitude': -7...",NaN
38,The Self Tape Space,"[W 118th St & Manhattan Ave, New York, NY 10026]",New York,5.0,13,"{'latitude': 40.806343, 'longitude': -73.955873}",NaN
39,Tom Ragan Films,"[Brooklyn, NY 11215]",Brooklyn,5.0,2,"{'latitude': 40.66889, 'longitude': -73.9819}",NaN
40,Fine Art Productions,"[1655 Oak Tree Rd, Ste 270, Edison, NJ 08820]",Edison,4.5,19,"{'latitude': 40.5709695115082, 'longitude': -7...",NaN
41,Hello Super Studios,"[Brooklyn, NY 11206]",Brooklyn,5.0,9,"{'latitude': 40.7038917541504, 'longitude': -7...",NaN
42,AbelCine,"[Industry City, 88 35th St, Fl 4, Brooklyn, NY...",Brooklyn,3.5,9,"{'latitude': 40.6564111, 'longitude': -74.0067...",4.0
43,Jersey Filmmaker,"[Jersey City, NJ 07302]",Jersey City,5.0,1,"{'latitude': 40.7218017578125, 'longitude': -7...",NaN
44,Latour de Force Productions,"[New York, NY 10019]",New York,5.0,7,"{'latitude': 40.7645378112793, 'longitude': -7...",NaN
45,Brain Fry Productions,"[2853 Steinway St, 2F, Astoria, NY 11103]",Astoria,5.0,2,"{'latitude': 40.630508, 'longitude': -74.028456}",NaN
46,Silvercup Studios,"[42-22 22nd St, Long Island City, NY 11101]",Long Island City,4.5,12,"{'latitude': 40.751331, 'longitude': -73.943515}",NaN
47,YouTube Space,"[75 9th Ave, New York, NY 10011]",New York,5.0,6,"{'latitude': 40.742581, 'longitude': -74.005434}",NaN
48,Sun Production,"[36-06 30th St, C7, Astoria, NY 11106]",Astoria,5.0,1,"{'latitude': 40.756815, 'longitude': -73.930988}",NaN
49,Broadway Stages,"[359 Kingsland Ave, Greenpoint, NY 11222]",Greenpoint,4.0,1,"{'latitude': 40.7289565103425, 'longitude': -7...",NaN

In [53]:
parsed

[('DiJiFi',
  ['1166 Manhattan Ave', 'Ste 201', 'Brooklyn, NY 11222'],
  'Brooklyn',
  4.5,
  165,
  {'latitude': 40.7382584, 'longitude': -73.9549479},
  2),
 ('590films',
  ['42 West St', 'Ste 301', 'Brooklyn, NY 11222'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.7280427, 'longitude': -73.9588363},
  None),
 ("Shell's Loft Brooklyn",
  ['13 Lexington Ave', 'Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  2,
  {'latitude': 40.6866128, 'longitude': -73.9616521},
  None),
 ('Mind of Who Productions',
  ['193 Marcus Garvey Blvd', 'Brooklyn, NY 11221'],
  'Brooklyn',
  4.5,
  2,
  {'latitude': 40.691765, 'longitude': -73.939434},
  None),
 ('Kaleidoscope Pictures',
  ['Brooklyn, NY 11231'],
  'Brooklyn',
  5.0,
  8,
  {'latitude': 40.6772802, 'longitude': -74.0094471},
  None),
 ('Cinema World Studios',
  ['220 Dupont St', 'Brooklyn, NY 11222'],
  'Brooklyn',
  4.5,
  2,
  {'latitude': 40.735954, 'longitude': -73.950508},
  None),
 ('Starr Street Media',
  ['852 Rogers Ave', 'Brooklyn, NY 11226'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.64986, 'longitude': -73.95257},
  None),
 ('Hit and Run Productions',
  ['65 Roebling St', 'Ste 202', 'Brooklyn, NY 11211'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.7165128, 'longitude': -73.9546435},
  None),
 ('BK Actors Self-Tape',
  ['141 Flushing Ave',
   'Bldg 77 ,Ste 1336',
   'Brooklyn Navy Yard',
   'Brooklyn, NY 11205'],
  'Brooklyn',
  5.0,
  14,
  {'latitude': 40.6985551, 'longitude': -73.9712029},
  None),
 ('Bizvidmedia Productions',
  ['99 Wallstreet', 'New York, NY 10005'],
  'New York',
  5.0,
  5,
  {'latitude': 40.70479, 'longitude': -74.00726},
  None),
 ('Indigo Productions',
  ['250 W 90th St', 'New York, NY 10024'],
  'New York',
  5.0,
  5,
  {'latitude': 40.7908706665039, 'longitude': -73.9751968383789},
  None),
 ('Silentface',
  ['86 Menahan St', 'Ste 2L', 'Brooklyn, NY 11221'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.69445, 'longitude': -73.92036},
  None),
 ('Killer Combo Studios',
  ['641 Classon Ave', 'Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  7,
  {'latitude': 40.678534, 'longitude': -73.958435},
  None),
 ('Iris Cinematics',
  ['121 Newark Ave', 'Ste 506', 'Jersey City, NJ 07302'],
  'Jersey City',
  5.0,
  1,
  {'latitude': 40.7199096679688, 'longitude': -74.0432891845703},
  None),
 ('Amy Lawday Films',
  ['Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.67772, 'longitude': -73.96312},
  None),
 ('An Olivetree Production',
  ['1350 Willoughby Ave', 'New York, NY 11237'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7061738002948, 'longitude': -73.9202935099089},
  None),
 ('Steiner Studios',
  ['15 Washington Ave', 'Brooklyn, NY 11205'],
  'Brooklyn',
  4.5,
  7,
  {'latitude': 40.6983157794782, 'longitude': -73.967696428299},
  None),
 ('Ground Glass Motion Picture Company',
  ['195 Christie St', 'New York, NY 10002'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7221489, 'longitude': -73.9923325},
  None),
 ('Vengo Films',
  ['8913 4th Ave', 'Ste 5837', 'Brooklyn, NY 11209'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.620018, 'longitude': -74.0292025},
  None),
 ('Urban Myth Studio',
  ['505 Johnson Ave', 'Brooklyn, NY 11237'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.708663918903, 'longitude': -73.926939086334},
  None),
 ('Automatic Studios',
  ['52 Bridge St', 'Brooklyn, NY 11201'],
  'Brooklyn',
  4.0,
  7,
  {'latitude': 40.703069, 'longitude': -73.98468},
  None),
 ('The Cubed Effect',
  ['New York, NY 11201'],
  'New York',
  5.0,
  4,
  {'latitude': 40.69347, 'longitude': -73.99052},
  None),
 ('Gee Media',
  ['Brooklyn, NY 11225'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.66363, 'longitude': -73.95541},
  None),
 ('Miller/Datri Entertainment',
  ['600 Fifth Ave', 'Fl 2', 'New York, NY 10020'],
  'New York',
  5.0,
  4,
  {'latitude': 40.758596, 'longitude': -73.9784575},
  None),
 ('Film Trade',
  ['86 Verona St', 'New York, NY 11231'],
  'New York',
  5.0,
  1,
  {'latitude': 40.6796212181687, 'longitude': -74.0091629592533},
  None),
 ('Hello World Communications',
  ['118 W 22nd St', 'Fl 2', 'New York, NY 10011'],
  'New York',
  5.0,
  42,
  {'latitude': 40.7425398, 'longitude': -73.9945521},
  None),
 ('RUX Media',
  ['50 Harrison St', 'Hoboken, NJ 07030'],
  'Hoboken',
  5.0,
  1,
  {'latitude': 40.7372343, 'longitude': -74.042797},
  None),
 ('And/With Creative',
  ['102 Bay Ridge Ave', 'Ste 2F', 'Brooklyn, NY 11220'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.63741, 'longitude': -74.03218},
  None),
 ('New York Film Shop',
  ['437 Washington St', 'New York, NY 10013'],
  'New York',
  5.0,
  3,
  {'latitude': 40.7232895, 'longitude': -74.0101166},
  None),
 ('GUM Studios',
  ['4508 2nd Ave', 'Brooklyn, NY 11232'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.65181, 'longitude': -74.0143},
  None),
 ('Cage Free Productions',
  ['15 Hawthorne St', 'Ste 3B', 'Brooklyn, NY 11225'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.657474, 'longitude': -73.959732},
  None),
 ('Starr Street Studios',
  ['207-A Starr St', 'Ste 3-1', 'Brooklyn, NY 11237'],
  'Brooklyn',
  5.0,
  8,
  {'latitude': 40.705122, 'longitude': -73.923457},
  None),
 ('The Edit Center',
  ['168 7th St', 'Ste 314', 'Brooklyn, NY 11215'],
  'Brooklyn',
  5.0,
  6,
  {'latitude': 40.6728208, 'longitude': -73.9909742},
  None),
 ('Muve Media',
  ['36 Waverly Ave', 'Brooklyn, NY 11205'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.696788, 'longitude': -73.968833},
  None),
 ('MRD Productions',
  ['500 W 30th St', 'New York, NY 10001'],
  'New York',
  5.0,
  1,
  {'latitude': 40.75194, 'longitude': -74.00156},
  None),
 ('V-Productions',
  ['469 7th Ave', 'New York, NY 10018'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7519226, 'longitude': -73.9894887},
  None),
 ('Deverge Studio',
  ['150 W 28th St', 'Ste 600', 'New York, NY 10001'],
  'New York',
  5.0,
  5,
  {'latitude': 40.74676, 'longitude': -73.99282},
  None),
 ('Eastern Effects',
  ['99 9th St', 'Brooklyn, NY 11215'],
  'Brooklyn',
  4.5,
  3,
  {'latitude': 40.6734029529525, 'longitude': -73.9946415645175},
  None),
 ('The Self Tape Space',
  ['W 118th St & Manhattan Ave', 'New York, NY 10026'],
  'New York',
  5.0,
  13,
  {'latitude': 40.806343, 'longitude': -73.955873},
  None),
 ('Tom Ragan Films',
  ['Brooklyn, NY 11215'],
  'Brooklyn',
  5.0,
  2,
  {'latitude': 40.66889, 'longitude': -73.9819},
  None),
 ('Fine Art Productions',
  ['1655 Oak Tree Rd', 'Ste 270', 'Edison, NJ 08820'],
  'Edison',
  4.5,
  19,
  {'latitude': 40.5709695115082, 'longitude': -74.340228068968},
  None),
 ('Hello Super Studios',
  ['Brooklyn, NY 11206'],
  'Brooklyn',
  5.0,
  9,
  {'latitude': 40.7038917541504, 'longitude': -73.9447479248047},
  None),
 ('AbelCine',
  ['Industry City', '88 35th St, Fl 4', 'Brooklyn, NY 11232'],
  'Brooklyn',
  3.5,
  9,
  {'latitude': 40.6564111, 'longitude': -74.0067047},
  4),
 ('Jersey Filmmaker',
  ['Jersey City, NJ 07302'],
  'Jersey City',
  5.0,
  1,
  {'latitude': 40.7218017578125, 'longitude': -74.0449295043945},
  None),
 ('Latour de Force Productions',
  ['New York, NY 10019'],
  'New York',
  5.0,
  7,
  {'latitude': 40.7645378112793, 'longitude': -73.9842376708984},
  None),
 ('Brain Fry Productions',
  ['2853 Steinway St', '2F', 'Astoria, NY 11103'],
  'Astoria',
  5.0,
  2,
  {'latitude': 40.630508, 'longitude': -74.028456},
  None),
 ('Silvercup Studios',
  ['42-22 22nd St', 'Long Island City, NY 11101'],
  'Long Island City',
  4.5,
  12,
  {'latitude': 40.751331, 'longitude': -73.943515},
  None),
 ('YouTube Space',
  ['75 9th Ave', 'New York, NY 10011'],
  'New York',
  5.0,
  6,
  {'latitude': 40.742581, 'longitude': -74.005434},
  None),
 ('Sun Production',
  ['36-06 30th St', 'C7', 'Astoria, NY 11106'],
  'Astoria',
  5.0,
  1,
  {'latitude': 40.756815, 'longitude': -73.930988},
  None),
 ('Broadway Stages',
  ['359 Kingsland Ave', 'Greenpoint, NY 11222'],
  'Greenpoint',
  4.0,
  1,
  {'latitude': 40.7289565103425, 'longitude': -73.9424950629473},
  None)]

In [54]:
type(len(df))

int

In [72]:
df = pd.DataFrame(data, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
results = yelp_call(headers, url_params)
parsed = parse_data(results['businesses'])
df_2 = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
df.append(df_2, ignore_index=True)
df

Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: []

### Testing for call_1000

In [72]:
df = pd.DataFrame(data, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
results = yelp_call(headers, url_params)
parsed = parse_data(results['businesses'])
df_2 = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
df.append(df_2, ignore_index=True)
df

Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: []

In [ ]:
csv_filepath = f'database/{term}_{location}_database.csv'

In [ ]:
current_offset = 0
url_params['offset'] = current_offset
results = yelp_call(headers, url_params)
parsed = parse_data(results['businesses'])
num = results['total']
df = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
while current_offset < (num+50) and current_offset < 1000:     

    
#         concat or append df here
#             current_offset += 50
#             url_params['offset'] = current_offset
#             results = yelp_call(headers, url_params)
#             parsed = parse_data(results['businesses'])

        df2 = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
        df.append(df2)
    current_offset += 50
    url_params['offset'] = current_offset
    results = yelp_call(headers, url_params)
    parsed = parse_data(results['businesses'])
return df

In [71]:
#testing call_1000() contents outside of function

current_offset = url_params['offset']
df = pd.DataFrame(data, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
num = 0
while current_offset < (num+1) and current_offset < 951: 
    url_params['offset'] = current_offset

    results = yelp_call(headers, url_params)
    parsed = parse_data(results['businesses'])
    #concat or append df here
    df_2 = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
    df.append(df_2, ignore_index=True)
#     num += len(df)
#     current_offset += 50
#     url_params['offset'] = current_offset
    print(df, current_offset, num, url_params)

Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}

KeyboardInterrupt:

In [29]:
pd.DataFrame(data)

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [103]:
# testing DataFrame output from parsed (parsed = parse_data(data['businesses']))

pd.DataFrame(parsed[0:3], columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])

,Name,Address,City,Rating,Review Count,Coordinates,Price
0,DiJiFi,"[1166 Manhattan Ave, Ste 201, Brooklyn, NY 11222]",Brooklyn,4.5,165,"{'latitude': 40.7382584, 'longitude': -73.9549...",2.0
1,590films,"[42 West St, Ste 301, Brooklyn, NY 11222]",Brooklyn,5.0,4,"{'latitude': 40.7280427, 'longitude': -73.9588...",NaN
2,Shell's Loft Brooklyn,"[13 Lexington Ave, Brooklyn, NY 11238]",Brooklyn,5.0,2,"{'latitude': 40.6866128, 'longitude': -73.9616...",NaN

In [117]:
# data['total']
yelp_call(headers, url_params)['total']

298

In [ ]:
# df = pd.DataFrame(parsed_results, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])

In [ ]:
# your code to open the csv file, concat the current data, and save the data. 

def df_save(csv_filepath, df): # MIKE NOTE: an if statement for if the file exists may be useful
    with open(csv_filepath, "a") as f: #'x' creates and writes to csv
        read_file = csv.writer(f)
        df.to_csv(csv_filepath, mode = "a", index = False)
# this will append to csv. 2nd arg index=False to not save the inde

In [ ]:
df_save(f'database/{term}_{location}_database.csv', df)

In [71]:
current_offset = url_params['offset']
df = pd.DataFrame(data, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
num = 0
while current_offset < (num+1) and current_offset < 951: 
    url_params['offset'] = current_offset

    results = yelp_call(headers, url_params)
    parsed = parse_data(results['businesses'])
    #concat or append df here
    df_2 = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
    df.append(df_2, ignore_index=True)
#     num += len(df)
#     current_offset += 50
#     url_params['offset'] = current_offset
    print(df, current_offset, num, url_params)

Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}
Empty DataFrame
Columns: [Name, Address, City, Rating, Review Count, Coordinates, Price]
Index: [] 0 0 {'term': 'Film+Production', 'location': 'Brooklyn', 'categories': 'Video/Film', 'limit': 50, 'offset': 0}

KeyboardInterrupt:

In [73]:
parsed = parse_data(data['businesses'])
parsed

[('DiJiFi',
  ['1166 Manhattan Ave', 'Ste 201', 'Brooklyn, NY 11222'],
  'Brooklyn',
  4.5,
  165,
  {'latitude': 40.7382584, 'longitude': -73.9549479},
  2),
 ('590films',
  ['42 West St', 'Ste 301', 'Brooklyn, NY 11222'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.7280427, 'longitude': -73.9588363},
  None),
 ("Shell's Loft Brooklyn",
  ['13 Lexington Ave', 'Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  2,
  {'latitude': 40.6866128, 'longitude': -73.9616521},
  None),
 ('Mind of Who Productions',
  ['193 Marcus Garvey Blvd', 'Brooklyn, NY 11221'],
  'Brooklyn',
  4.5,
  2,
  {'latitude': 40.691765, 'longitude': -73.939434},
  None),
 ('Kaleidoscope Pictures',
  ['Brooklyn, NY 11231'],
  'Brooklyn',
  5.0,
  8,
  {'latitude': 40.6772802, 'longitude': -74.0094471},
  None),
 ('Cinema World Studios',
  ['220 Dupont St', 'Brooklyn, NY 11222'],
  'Brooklyn',
  4.5,
  2,
  {'latitude': 40.735954, 'longitude': -73.950508},
  None),
 ('Starr Street Media',
  ['852 Rogers Ave', 'Brooklyn, NY 11226'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.64986, 'longitude': -73.95257},
  None),
 ('Hit and Run Productions',
  ['65 Roebling St', 'Ste 202', 'Brooklyn, NY 11211'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.7165128, 'longitude': -73.9546435},
  None),
 ('BK Actors Self-Tape',
  ['141 Flushing Ave',
   'Bldg 77 ,Ste 1336',
   'Brooklyn Navy Yard',
   'Brooklyn, NY 11205'],
  'Brooklyn',
  5.0,
  14,
  {'latitude': 40.6985551, 'longitude': -73.9712029},
  None),
 ('Bizvidmedia Productions',
  ['99 Wallstreet', 'New York, NY 10005'],
  'New York',
  5.0,
  5,
  {'latitude': 40.70479, 'longitude': -74.00726},
  None),
 ('Indigo Productions',
  ['250 W 90th St', 'New York, NY 10024'],
  'New York',
  5.0,
  5,
  {'latitude': 40.7908706665039, 'longitude': -73.9751968383789},
  None),
 ('Silentface',
  ['86 Menahan St', 'Ste 2L', 'Brooklyn, NY 11221'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.69445, 'longitude': -73.92036},
  None),
 ('Killer Combo Studios',
  ['641 Classon Ave', 'Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  7,
  {'latitude': 40.678534, 'longitude': -73.958435},
  None),
 ('Iris Cinematics',
  ['121 Newark Ave', 'Ste 506', 'Jersey City, NJ 07302'],
  'Jersey City',
  5.0,
  1,
  {'latitude': 40.7199096679688, 'longitude': -74.0432891845703},
  None),
 ('Amy Lawday Films',
  ['Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.67772, 'longitude': -73.96312},
  None),
 ('An Olivetree Production',
  ['1350 Willoughby Ave', 'New York, NY 11237'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7061738002948, 'longitude': -73.9202935099089},
  None),
 ('Steiner Studios',
  ['15 Washington Ave', 'Brooklyn, NY 11205'],
  'Brooklyn',
  4.5,
  7,
  {'latitude': 40.6983157794782, 'longitude': -73.967696428299},
  None),
 ('Ground Glass Motion Picture Company',
  ['195 Christie St', 'New York, NY 10002'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7221489, 'longitude': -73.9923325},
  None),
 ('Vengo Films',
  ['8913 4th Ave', 'Ste 5837', 'Brooklyn, NY 11209'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.620018, 'longitude': -74.0292025},
  None),
 ('Urban Myth Studio',
  ['505 Johnson Ave', 'Brooklyn, NY 11237'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.708663918903, 'longitude': -73.926939086334},
  None),
 ('Automatic Studios',
  ['52 Bridge St', 'Brooklyn, NY 11201'],
  'Brooklyn',
  4.0,
  7,
  {'latitude': 40.703069, 'longitude': -73.98468},
  None),
 ('The Cubed Effect',
  ['New York, NY 11201'],
  'New York',
  5.0,
  4,
  {'latitude': 40.69347, 'longitude': -73.99052},
  None),
 ('Gee Media',
  ['Brooklyn, NY 11225'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.66363, 'longitude': -73.95541},
  None),
 ('Miller/Datri Entertainment',
  ['600 Fifth Ave', 'Fl 2', 'New York, NY 10020'],
  'New York',
  5.0,
  4,
  {'latitude': 40.758596, 'longitude': -73.9784575},
  None),
 ('Film Trade',
  ['86 Verona St', 'New York, NY 11231'],
  'New York',
  5.0,
  1,
  {'latitude': 40.6796212181687, 'longitude': -74.0091629592533},
  None),
 ('Hello World Communications',
  ['118 W 22nd St', 'Fl 2', 'New York, NY 10011'],
  'New York',
  5.0,
  42,
  {'latitude': 40.7425398, 'longitude': -73.9945521},
  None),
 ('RUX Media',
  ['50 Harrison St', 'Hoboken, NJ 07030'],
  'Hoboken',
  5.0,
  1,
  {'latitude': 40.7372343, 'longitude': -74.042797},
  None),
 ('And/With Creative',
  ['102 Bay Ridge Ave', 'Ste 2F', 'Brooklyn, NY 11220'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.63741, 'longitude': -74.03218},
  None),
 ('New York Film Shop',
  ['437 Washington St', 'New York, NY 10013'],
  'New York',
  5.0,
  3,
  {'latitude': 40.7232895, 'longitude': -74.0101166},
  None),
 ('GUM Studios',
  ['4508 2nd Ave', 'Brooklyn, NY 11232'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.65181, 'longitude': -74.0143},
  None),
 ('Cage Free Productions',
  ['15 Hawthorne St', 'Ste 3B', 'Brooklyn, NY 11225'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.657474, 'longitude': -73.959732},
  None),
 ('Starr Street Studios',
  ['207-A Starr St', 'Ste 3-1', 'Brooklyn, NY 11237'],
  'Brooklyn',
  5.0,
  8,
  {'latitude': 40.705122, 'longitude': -73.923457},
  None),
 ('The Edit Center',
  ['168 7th St', 'Ste 314', 'Brooklyn, NY 11215'],
  'Brooklyn',
  5.0,
  6,
  {'latitude': 40.6728208, 'longitude': -73.9909742},
  None),
 ('Muve Media',
  ['36 Waverly Ave', 'Brooklyn, NY 11205'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.696788, 'longitude': -73.968833},
  None),
 ('MRD Productions',
  ['500 W 30th St', 'New York, NY 10001'],
  'New York',
  5.0,
  1,
  {'latitude': 40.75194, 'longitude': -74.00156},
  None),
 ('V-Productions',
  ['469 7th Ave', 'New York, NY 10018'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7519226, 'longitude': -73.9894887},
  None),
 ('Deverge Studio',
  ['150 W 28th St', 'Ste 600', 'New York, NY 10001'],
  'New York',
  5.0,
  5,
  {'latitude': 40.74676, 'longitude': -73.99282},
  None),
 ('Eastern Effects',
  ['99 9th St', 'Brooklyn, NY 11215'],
  'Brooklyn',
  4.5,
  3,
  {'latitude': 40.6734029529525, 'longitude': -73.9946415645175},
  None),
 ('The Self Tape Space',
  ['W 118th St & Manhattan Ave', 'New York, NY 10026'],
  'New York',
  5.0,
  13,
  {'latitude': 40.806343, 'longitude': -73.955873},
  None),
 ('Tom Ragan Films',
  ['Brooklyn, NY 11215'],
  'Brooklyn',
  5.0,
  2,
  {'latitude': 40.66889, 'longitude': -73.9819},
  None),
 ('Fine Art Productions',
  ['1655 Oak Tree Rd', 'Ste 270', 'Edison, NJ 08820'],
  'Edison',
  4.5,
  19,
  {'latitude': 40.5709695115082, 'longitude': -74.340228068968},
  None),
 ('Hello Super Studios',
  ['Brooklyn, NY 11206'],
  'Brooklyn',
  5.0,
  9,
  {'latitude': 40.7038917541504, 'longitude': -73.9447479248047},
  None),
 ('AbelCine',
  ['Industry City', '88 35th St, Fl 4', 'Brooklyn, NY 11232'],
  'Brooklyn',
  3.5,
  9,
  {'latitude': 40.6564111, 'longitude': -74.0067047},
  4),
 ('Jersey Filmmaker',
  ['Jersey City, NJ 07302'],
  'Jersey City',
  5.0,
  1,
  {'latitude': 40.7218017578125, 'longitude': -74.0449295043945},
  None),
 ('Latour de Force Productions',
  ['New York, NY 10019'],
  'New York',
  5.0,
  7,
  {'latitude': 40.7645378112793, 'longitude': -73.9842376708984},
  None),
 ('Brain Fry Productions',
  ['2853 Steinway St', '2F', 'Astoria, NY 11103'],
  'Astoria',
  5.0,
  2,
  {'latitude': 40.630508, 'longitude': -74.028456},
  None),
 ('Silvercup Studios',
  ['42-22 22nd St', 'Long Island City, NY 11101'],
  'Long Island City',
  4.5,
  12,
  {'latitude': 40.751331, 'longitude': -73.943515},
  None),
 ('YouTube Space',
  ['75 9th Ave', 'New York, NY 10011'],
  'New York',
  5.0,
  6,
  {'latitude': 40.742581, 'longitude': -74.005434},
  None),
 ('Sun Production',
  ['36-06 30th St', 'C7', 'Astoria, NY 11106'],
  'Astoria',
  5.0,
  1,
  {'latitude': 40.756815, 'longitude': -73.930988},
  None),
 ('Broadway Stages',
  ['359 Kingsland Ave', 'Greenpoint, NY 11222'],
  'Greenpoint',
  4.0,
  1,
  {'latitude': 40.7289565103425, 'longitude': -73.9424950629473},
  None)]

In [74]:
pd.DataFrame(parsed, columns =['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])

,Name,Address,City,Rating,Review Count,Coordinates,Price
0,DiJiFi,"[1166 Manhattan Ave, Ste 201, Brooklyn, NY 11222]",Brooklyn,4.5,165,"{'latitude': 40.7382584, 'longitude': -73.9549...",2.0
1,590films,"[42 West St, Ste 301, Brooklyn, NY 11222]",Brooklyn,5.0,4,"{'latitude': 40.7280427, 'longitude': -73.9588...",NaN
2,Shell's Loft Brooklyn,"[13 Lexington Ave, Brooklyn, NY 11238]",Brooklyn,5.0,2,"{'latitude': 40.6866128, 'longitude': -73.9616...",NaN
3,Mind of Who Productions,"[193 Marcus Garvey Blvd, Brooklyn, NY 11221]",Brooklyn,4.5,2,"{'latitude': 40.691765, 'longitude': -73.939434}",NaN
4,Kaleidoscope Pictures,"[Brooklyn, NY 11231]",Brooklyn,5.0,8,"{'latitude': 40.6772802, 'longitude': -74.0094...",NaN
5,Cinema World Studios,"[220 Dupont St, Brooklyn, NY 11222]",Brooklyn,4.5,2,"{'latitude': 40.735954, 'longitude': -73.950508}",NaN
6,Starr Street Media,"[852 Rogers Ave, Brooklyn, NY 11226]",Brooklyn,5.0,1,"{'latitude': 40.64986, 'longitude': -73.95257}",NaN
7,Hit and Run Productions,"[65 Roebling St, Ste 202, Brooklyn, NY 11211]",Brooklyn,5.0,4,"{'latitude': 40.7165128, 'longitude': -73.9546...",NaN
8,BK Actors Self-Tape,"[141 Flushing Ave, Bldg 77 ,Ste 1336, Brooklyn...",Brooklyn,5.0,14,"{'latitude': 40.6985551, 'longitude': -73.9712...",NaN
9,Bizvidmedia Productions,"[99 Wallstreet, New York, NY 10005]",New York,5.0,5,"{'latitude': 40.70479, 'longitude': -74.00726}",NaN
10,Indigo Productions,"[250 W 90th St, New York, NY 10024]",New York,5.0,5,"{'latitude': 40.7908706665039, 'longitude': -7...",NaN
11,Silentface,"[86 Menahan St, Ste 2L, Brooklyn, NY 11221]",Brooklyn,5.0,1,"{'latitude': 40.69445, 'longitude': -73.92036}",NaN
12,Killer Combo Studios,"[641 Classon Ave, Brooklyn, NY 11238]",Brooklyn,5.0,7,"{'latitude': 40.678534, 'longitude': -73.958435}",NaN
13,Iris Cinematics,"[121 Newark Ave, Ste 506, Jersey City, NJ 07302]",Jersey City,5.0,1,"{'latitude': 40.7199096679688, 'longitude': -7...",NaN
14,Amy Lawday Films,"[Brooklyn, NY 11238]",Brooklyn,5.0,1,"{'latitude': 40.67772, 'longitude': -73.96312}",NaN
15,An Olivetree Production,"[1350 Willoughby Ave, New York, NY 11237]",New York,5.0,1,"{'latitude': 40.7061738002948, 'longitude': -7...",NaN
16,Steiner Studios,"[15 Washington Ave, Brooklyn, NY 11205]",Brooklyn,4.5,7,"{'latitude': 40.6983157794782, 'longitude': -7...",NaN
17,Ground Glass Motion Picture Company,"[195 Christie St, New York, NY 10002]",New York,5.0,1,"{'latitude': 40.7221489, 'longitude': -73.9923...",NaN
18,Vengo Films,"[8913 4th Ave, Ste 5837, Brooklyn, NY 11209]",Brooklyn,5.0,1,"{'latitude': 40.620018, 'longitude': -74.0292025}",NaN
19,Urban Myth Studio,"[505 Johnson Ave, Brooklyn, NY 11237]",Brooklyn,5.0,4,"{'latitude': 40.708663918903, 'longitude': -73...",NaN
20,Automatic Studios,"[52 Bridge St, Brooklyn, NY 11201]",Brooklyn,4.0,7,"{'latitude': 40.703069, 'longitude': -73.98468}",NaN
21,The Cubed Effect,"[New York, NY 11201]",New York,5.0,4,"{'latitude': 40.69347, 'longitude': -73.99052}",NaN
22,Gee Media,"[Brooklyn, NY 11225]",Brooklyn,5.0,4,"{'latitude': 40.66363, 'longitude': -73.95541}",NaN
23,Miller/Datri Entertainment,"[600 Fifth Ave, Fl 2, New York, NY 10020]",New York,5.0,4,"{'latitude': 40.758596, 'longitude': -73.9784575}",NaN
24,Film Trade,"[86 Verona St, New York, NY 11231]",New York,5.0,1,"{'latitude': 40.6796212181687, 'longitude': -7...",NaN
25,Hello World Communications,"[118 W 22nd St, Fl 2, New York, NY 10011]",New York,5.0,42,"{'latitude': 40.7425398, 'longitude': -73.9945...",NaN
26,RUX Media,"[50 Harrison St, Hoboken, NJ 07030]",Hoboken,5.0,1,"{'latitude': 40.7372343, 'longitude': -74.042797}",NaN
27,And/With Creative,"[102 Bay Ridge Ave, Ste 2F, Brooklyn, NY 11220]",Brooklyn,5.0,1,"{'latitude': 40.63741, 'longitude': -74.03218}",NaN
28,New York Film Shop,"[437 Washington St, New York, NY 10013]",New York,5.0,3,"{'latitude': 40.7232895, 'longitude': -74.0101...",NaN
29,GUM Studios,"[4508 2nd Ave, Brooklyn, NY 11232]",Brooklyn,5.0,1,"{'latitude': 40.65181, 'longitude': -74.0143}",NaN
30,Cage Free Productions,"[15 Hawthorne St, Ste 3B, Brooklyn, NY 11225]",Brooklyn,5.0,1,"{'latitude': 40.657474, 'longitude': -73.959732}",NaN
31,Starr Street Studios,"[207-A Starr St, Ste 3-1, Brooklyn, NY 11237]",Brooklyn,5.0,8,"{'latitude': 40.705122, 'longitude': -73.923457}",NaN
32,The Edit Center,"[168 7th St, Ste 314, Brooklyn, NY 11215]",Brooklyn,5.0,6,"{'latitude': 40.6728208, 'longitude': -73.9909...",NaN
33,Muve Media,"[36 Waverly Ave, Brooklyn, NY 11205]",Brooklyn,5.0,1,"{'latitude': 40.696788, 'longitude': -73.968833}",NaN
34,MRD Productions,"[500 W 30th St, New York, NY 10001]",New York,5.0,1,"{'latitude': 40.75194, 'longitude': -74.00156}",NaN
35,V-Productions,"[469 7th Ave, New York, NY 10018]",New York,5.0,1,"{'latitude': 40.7519226, 'longitude': -73.9894...",NaN
36,Deverge Studio,"[150 W 28th St, Ste 600, New York, NY 10001]",New York,5.0,5,"{'latitude': 40.74676, 'longitude': -73.99282}",NaN
37,Eastern Effects,"[99 9th St, Brooklyn, NY 11215]",Brooklyn,4.5,3,"{'latitude': 40.6734029529525, 'longitude': -7...",NaN
38,The Self Tape Space,"[W 118th St & Manhattan Ave, New York, NY 10026]",New York,5.0,13,"{'latitude': 40.806343, 'longitude': -73.955873}",NaN
39,Tom Ragan Films,"[Brooklyn, NY 11215]",Brooklyn,5.0,2,"{'latitude': 40.66889, 'longitude': -73.9819}",NaN
40,Fine Art Productions,"[1655 Oak Tree Rd, Ste 270, Edison, NJ 08820]",Edison,4.5,19,"{'latitude': 40.5709695115082, 'longitude': -7...",NaN
41,Hello Super Studios,"[Brooklyn, NY 11206]",Brooklyn,5.0,9,"{'latitude': 40.7038917541504, 'longitude': -7...",NaN
42,AbelCine,"[Industry City, 88 35th St, Fl 4, Brooklyn, NY...",Brooklyn,3.5,9,"{'latitude': 40.6564111, 'longitude': -74.0067...",4.0
43,Jersey Filmmaker,"[Jersey City, NJ 07302]",Jersey City,5.0,1,"{'latitude': 40.7218017578125, 'longitude': -7...",NaN
44,Latour de Force Productions,"[New York, NY 10019]",New York,5.0,7,"{'latitude': 40.7645378112793, 'longitude': -7...",NaN
45,Brain Fry Productions,"[2853 Steinway St, 2F, Astoria, NY 11103]",Astoria,5.0,2,"{'latitude': 40.630508, 'longitude': -74.028456}",NaN
46,Silvercup Studios,"[42-22 22nd St, Long Island City, NY 11101]",Long Island City,4.5,12,"{'latitude': 40.751331, 'longitude': -73.943515}",NaN
47,YouTube Space,"[75 9th Ave, New York, NY 10011]",New York,5.0,6,"{'latitude': 40.742581, 'longitude': -74.005434}",NaN
48,Sun Production,"[36-06 30th St, C7, Astoria, NY 11106]",Astoria,5.0,1,"{'latitude': 40.756815, 'longitude': -73.930988}",NaN
49,Broadway Stages,"[359 Kingsland Ave, Greenpoint, NY 11222]",Greenpoint,4.0,1,"{'latitude': 40.7289565103425, 'longitude': -7...",NaN

In [53]:
parsed

[('DiJiFi',
  ['1166 Manhattan Ave', 'Ste 201', 'Brooklyn, NY 11222'],
  'Brooklyn',
  4.5,
  165,
  {'latitude': 40.7382584, 'longitude': -73.9549479},
  2),
 ('590films',
  ['42 West St', 'Ste 301', 'Brooklyn, NY 11222'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.7280427, 'longitude': -73.9588363},
  None),
 ("Shell's Loft Brooklyn",
  ['13 Lexington Ave', 'Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  2,
  {'latitude': 40.6866128, 'longitude': -73.9616521},
  None),
 ('Mind of Who Productions',
  ['193 Marcus Garvey Blvd', 'Brooklyn, NY 11221'],
  'Brooklyn',
  4.5,
  2,
  {'latitude': 40.691765, 'longitude': -73.939434},
  None),
 ('Kaleidoscope Pictures',
  ['Brooklyn, NY 11231'],
  'Brooklyn',
  5.0,
  8,
  {'latitude': 40.6772802, 'longitude': -74.0094471},
  None),
 ('Cinema World Studios',
  ['220 Dupont St', 'Brooklyn, NY 11222'],
  'Brooklyn',
  4.5,
  2,
  {'latitude': 40.735954, 'longitude': -73.950508},
  None),
 ('Starr Street Media',
  ['852 Rogers Ave', 'Brooklyn, NY 11226'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.64986, 'longitude': -73.95257},
  None),
 ('Hit and Run Productions',
  ['65 Roebling St', 'Ste 202', 'Brooklyn, NY 11211'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.7165128, 'longitude': -73.9546435},
  None),
 ('BK Actors Self-Tape',
  ['141 Flushing Ave',
   'Bldg 77 ,Ste 1336',
   'Brooklyn Navy Yard',
   'Brooklyn, NY 11205'],
  'Brooklyn',
  5.0,
  14,
  {'latitude': 40.6985551, 'longitude': -73.9712029},
  None),
 ('Bizvidmedia Productions',
  ['99 Wallstreet', 'New York, NY 10005'],
  'New York',
  5.0,
  5,
  {'latitude': 40.70479, 'longitude': -74.00726},
  None),
 ('Indigo Productions',
  ['250 W 90th St', 'New York, NY 10024'],
  'New York',
  5.0,
  5,
  {'latitude': 40.7908706665039, 'longitude': -73.9751968383789},
  None),
 ('Silentface',
  ['86 Menahan St', 'Ste 2L', 'Brooklyn, NY 11221'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.69445, 'longitude': -73.92036},
  None),
 ('Killer Combo Studios',
  ['641 Classon Ave', 'Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  7,
  {'latitude': 40.678534, 'longitude': -73.958435},
  None),
 ('Iris Cinematics',
  ['121 Newark Ave', 'Ste 506', 'Jersey City, NJ 07302'],
  'Jersey City',
  5.0,
  1,
  {'latitude': 40.7199096679688, 'longitude': -74.0432891845703},
  None),
 ('Amy Lawday Films',
  ['Brooklyn, NY 11238'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.67772, 'longitude': -73.96312},
  None),
 ('An Olivetree Production',
  ['1350 Willoughby Ave', 'New York, NY 11237'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7061738002948, 'longitude': -73.9202935099089},
  None),
 ('Steiner Studios',
  ['15 Washington Ave', 'Brooklyn, NY 11205'],
  'Brooklyn',
  4.5,
  7,
  {'latitude': 40.6983157794782, 'longitude': -73.967696428299},
  None),
 ('Ground Glass Motion Picture Company',
  ['195 Christie St', 'New York, NY 10002'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7221489, 'longitude': -73.9923325},
  None),
 ('Vengo Films',
  ['8913 4th Ave', 'Ste 5837', 'Brooklyn, NY 11209'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.620018, 'longitude': -74.0292025},
  None),
 ('Urban Myth Studio',
  ['505 Johnson Ave', 'Brooklyn, NY 11237'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.708663918903, 'longitude': -73.926939086334},
  None),
 ('Automatic Studios',
  ['52 Bridge St', 'Brooklyn, NY 11201'],
  'Brooklyn',
  4.0,
  7,
  {'latitude': 40.703069, 'longitude': -73.98468},
  None),
 ('The Cubed Effect',
  ['New York, NY 11201'],
  'New York',
  5.0,
  4,
  {'latitude': 40.69347, 'longitude': -73.99052},
  None),
 ('Gee Media',
  ['Brooklyn, NY 11225'],
  'Brooklyn',
  5.0,
  4,
  {'latitude': 40.66363, 'longitude': -73.95541},
  None),
 ('Miller/Datri Entertainment',
  ['600 Fifth Ave', 'Fl 2', 'New York, NY 10020'],
  'New York',
  5.0,
  4,
  {'latitude': 40.758596, 'longitude': -73.9784575},
  None),
 ('Film Trade',
  ['86 Verona St', 'New York, NY 11231'],
  'New York',
  5.0,
  1,
  {'latitude': 40.6796212181687, 'longitude': -74.0091629592533},
  None),
 ('Hello World Communications',
  ['118 W 22nd St', 'Fl 2', 'New York, NY 10011'],
  'New York',
  5.0,
  42,
  {'latitude': 40.7425398, 'longitude': -73.9945521},
  None),
 ('RUX Media',
  ['50 Harrison St', 'Hoboken, NJ 07030'],
  'Hoboken',
  5.0,
  1,
  {'latitude': 40.7372343, 'longitude': -74.042797},
  None),
 ('And/With Creative',
  ['102 Bay Ridge Ave', 'Ste 2F', 'Brooklyn, NY 11220'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.63741, 'longitude': -74.03218},
  None),
 ('New York Film Shop',
  ['437 Washington St', 'New York, NY 10013'],
  'New York',
  5.0,
  3,
  {'latitude': 40.7232895, 'longitude': -74.0101166},
  None),
 ('GUM Studios',
  ['4508 2nd Ave', 'Brooklyn, NY 11232'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.65181, 'longitude': -74.0143},
  None),
 ('Cage Free Productions',
  ['15 Hawthorne St', 'Ste 3B', 'Brooklyn, NY 11225'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.657474, 'longitude': -73.959732},
  None),
 ('Starr Street Studios',
  ['207-A Starr St', 'Ste 3-1', 'Brooklyn, NY 11237'],
  'Brooklyn',
  5.0,
  8,
  {'latitude': 40.705122, 'longitude': -73.923457},
  None),
 ('The Edit Center',
  ['168 7th St', 'Ste 314', 'Brooklyn, NY 11215'],
  'Brooklyn',
  5.0,
  6,
  {'latitude': 40.6728208, 'longitude': -73.9909742},
  None),
 ('Muve Media',
  ['36 Waverly Ave', 'Brooklyn, NY 11205'],
  'Brooklyn',
  5.0,
  1,
  {'latitude': 40.696788, 'longitude': -73.968833},
  None),
 ('MRD Productions',
  ['500 W 30th St', 'New York, NY 10001'],
  'New York',
  5.0,
  1,
  {'latitude': 40.75194, 'longitude': -74.00156},
  None),
 ('V-Productions',
  ['469 7th Ave', 'New York, NY 10018'],
  'New York',
  5.0,
  1,
  {'latitude': 40.7519226, 'longitude': -73.9894887},
  None),
 ('Deverge Studio',
  ['150 W 28th St', 'Ste 600', 'New York, NY 10001'],
  'New York',
  5.0,
  5,
  {'latitude': 40.74676, 'longitude': -73.99282},
  None),
 ('Eastern Effects',
  ['99 9th St', 'Brooklyn, NY 11215'],
  'Brooklyn',
  4.5,
  3,
  {'latitude': 40.6734029529525, 'longitude': -73.9946415645175},
  None),
 ('The Self Tape Space',
  ['W 118th St & Manhattan Ave', 'New York, NY 10026'],
  'New York',
  5.0,
  13,
  {'latitude': 40.806343, 'longitude': -73.955873},
  None),
 ('Tom Ragan Films',
  ['Brooklyn, NY 11215'],
  'Brooklyn',
  5.0,
  2,
  {'latitude': 40.66889, 'longitude': -73.9819},
  None),
 ('Fine Art Productions',
  ['1655 Oak Tree Rd', 'Ste 270', 'Edison, NJ 08820'],
  'Edison',
  4.5,
  19,
  {'latitude': 40.5709695115082, 'longitude': -74.340228068968},
  None),
 ('Hello Super Studios',
  ['Brooklyn, NY 11206'],
  'Brooklyn',
  5.0,
  9,
  {'latitude': 40.7038917541504, 'longitude': -73.9447479248047},
  None),
 ('AbelCine',
  ['Industry City', '88 35th St, Fl 4', 'Brooklyn, NY 11232'],
  'Brooklyn',
  3.5,
  9,
  {'latitude': 40.6564111, 'longitude': -74.0067047},
  4),
 ('Jersey Filmmaker',
  ['Jersey City, NJ 07302'],
  'Jersey City',
  5.0,
  1,
  {'latitude': 40.7218017578125, 'longitude': -74.0449295043945},
  None),
 ('Latour de Force Productions',
  ['New York, NY 10019'],
  'New York',
  5.0,
  7,
  {'latitude': 40.7645378112793, 'longitude': -73.9842376708984},
  None),
 ('Brain Fry Productions',
  ['2853 Steinway St', '2F', 'Astoria, NY 11103'],
  'Astoria',
  5.0,
  2,
  {'latitude': 40.630508, 'longitude': -74.028456},
  None),
 ('Silvercup Studios',
  ['42-22 22nd St', 'Long Island City, NY 11101'],
  'Long Island City',
  4.5,
  12,
  {'latitude': 40.751331, 'longitude': -73.943515},
  None),
 ('YouTube Space',
  ['75 9th Ave', 'New York, NY 10011'],
  'New York',
  5.0,
  6,
  {'latitude': 40.742581, 'longitude': -74.005434},
  None),
 ('Sun Production',
  ['36-06 30th St', 'C7', 'Astoria, NY 11106'],
  'Astoria',
  5.0,
  1,
  {'latitude': 40.756815, 'longitude': -73.930988},
  None),
 ('Broadway Stages',
  ['359 Kingsland Ave', 'Greenpoint, NY 11222'],
  'Greenpoint',
  4.0,
  1,
  {'latitude': 40.7289565103425, 'longitude': -73.9424950629473},
  None)]

In [54]:
type(len(df))

int

In [204]:
called_1k = call_1000()

In [127]:
parsed
test_d = pd.DataFrame
test_d2 = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
pd.concat([test_d, parsed])
test_d
type(parsed)

TypeError: _consolidate() missing 1 required positional argument: 'self'

In [205]:
called_1k.iloc[45:60]

,Name,Address,City,Rating,Review Count,Coordinates,Price
45,Brain Fry Productions,"[2853 Steinway St, 2F, Astoria, NY 11103]",Astoria,5.0,2,"{'latitude': 40.630508, 'longitude': -74.028456}",NaN
46,Silvercup Studios,"[42-22 22nd St, Long Island City, NY 11101]",Long Island City,4.5,12,"{'latitude': 40.751331, 'longitude': -73.943515}",NaN
47,YouTube Space,"[75 9th Ave, New York, NY 10011]",New York,5.0,6,"{'latitude': 40.742581, 'longitude': -74.005434}",NaN
48,Sun Production,"[36-06 30th St, C7, Astoria, NY 11106]",Astoria,5.0,1,"{'latitude': 40.756815, 'longitude': -73.930988}",NaN
49,Broadway Stages,"[359 Kingsland Ave, Greenpoint, NY 11222]",Greenpoint,4.0,1,"{'latitude': 40.7289565103425, 'longitude': -7...",NaN

In [163]:
test_parsed = parse_data(results['businesses'])
test_parsed
test_d = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
test_d.append(parsed)

,0,1,2,3,4,5,6,Address,City,Coordinates,Name,Price,Rating,Review Count
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1166 Manhattan Ave, Ste 201, Brooklyn, NY 11222]",Brooklyn,"{'latitude': 40.7382584, 'longitude': -73.9549...",DiJiFi,2.0,4.5,165.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[42 West St, Ste 301, Brooklyn, NY 11222]",Brooklyn,"{'latitude': 40.7280427, 'longitude': -73.9588...",590films,NaN,5.0,4.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[13 Lexington Ave, Brooklyn, NY 11238]",Brooklyn,"{'latitude': 40.6866128, 'longitude': -73.9616...",Shell's Loft Brooklyn,NaN,5.0,2.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[193 Marcus Garvey Blvd, Brooklyn, NY 11221]",Brooklyn,"{'latitude': 40.691765, 'longitude': -73.939434}",Mind of Who Productions,NaN,4.5,2.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Brooklyn, NY 11231]",Brooklyn,"{'latitude': 40.6772802, 'longitude': -74.0094...",Kaleidoscope Pictures,NaN,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,Brain Fry Productions,"[2853 Steinway St, 2F, Astoria, NY 11103]",Astoria,5.0,2.0,"{'latitude': 40.630508, 'longitude': -74.028456}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Silvercup Studios,"[42-22 22nd St, Long Island City, NY 11101]",Long Island City,4.5,12.0,"{'latitude': 40.751331, 'longitude': -73.943515}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,YouTube Space,"[75 9th Ave, New York, NY 10011]",New York,5.0,6.0,"{'latitude': 40.742581, 'longitude': -74.005434}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Sun Production,"[36-06 30th St, C7, Astoria, NY 11106]",Astoria,5.0,1.0,"{'latitude': 40.756815, 'longitude': -73.930988}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Broadway Stages,"[359 Kingsland Ave, Greenpoint, NY 11222]",Greenpoint,4.0,1.0,"{'latitude': 40.7289565103425, 'longitude': -7...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [185]:
df = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
df

,Name,Address,City,Rating,Review Count,Coordinates,Price
0,DiJiFi,"[1166 Manhattan Ave, Ste 201, Brooklyn, NY 11222]",Brooklyn,4.5,165,"{'latitude': 40.7382584, 'longitude': -73.9549...",2.0
1,590films,"[42 West St, Ste 301, Brooklyn, NY 11222]",Brooklyn,5.0,4,"{'latitude': 40.7280427, 'longitude': -73.9588...",NaN
2,Shell's Loft Brooklyn,"[13 Lexington Ave, Brooklyn, NY 11238]",Brooklyn,5.0,2,"{'latitude': 40.6866128, 'longitude': -73.9616...",NaN
3,Mind of Who Productions,"[193 Marcus Garvey Blvd, Brooklyn, NY 11221]",Brooklyn,4.5,2,"{'latitude': 40.691765, 'longitude': -73.939434}",NaN
4,Kaleidoscope Pictures,"[Brooklyn, NY 11231]",Brooklyn,5.0,8,"{'latitude': 40.6772802, 'longitude': -74.0094...",NaN
5,Cinema World Studios,"[220 Dupont St, Brooklyn, NY 11222]",Brooklyn,4.5,2,"{'latitude': 40.735954, 'longitude': -73.950508}",NaN
6,Starr Street Media,"[852 Rogers Ave, Brooklyn, NY 11226]",Brooklyn,5.0,1,"{'latitude': 40.64986, 'longitude': -73.95257}",NaN
7,Hit and Run Productions,"[65 Roebling St, Ste 202, Brooklyn, NY 11211]",Brooklyn,5.0,4,"{'latitude': 40.7165128, 'longitude': -73.9546...",NaN
8,BK Actors Self-Tape,"[141 Flushing Ave, Bldg 77 ,Ste 1336, Brooklyn...",Brooklyn,5.0,14,"{'latitude': 40.6985551, 'longitude': -73.9712...",NaN
9,Bizvidmedia Productions,"[99 Wallstreet, New York, NY 10005]",New York,5.0,5,"{'latitude': 40.70479, 'longitude': -74.00726}",NaN
10,Indigo Productions,"[250 W 90th St, New York, NY 10024]",New York,5.0,5,"{'latitude': 40.7908706665039, 'longitude': -7...",NaN
11,Silentface,"[86 Menahan St, Ste 2L, Brooklyn, NY 11221]",Brooklyn,5.0,1,"{'latitude': 40.69445, 'longitude': -73.92036}",NaN
12,Killer Combo Studios,"[641 Classon Ave, Brooklyn, NY 11238]",Brooklyn,5.0,7,"{'latitude': 40.678534, 'longitude': -73.958435}",NaN
13,Iris Cinematics,"[121 Newark Ave, Ste 506, Jersey City, NJ 07302]",Jersey City,5.0,1,"{'latitude': 40.7199096679688, 'longitude': -7...",NaN
14,Amy Lawday Films,"[Brooklyn, NY 11238]",Brooklyn,5.0,1,"{'latitude': 40.67772, 'longitude': -73.96312}",NaN
15,An Olivetree Production,"[1350 Willoughby Ave, New York, NY 11237]",New York,5.0,1,"{'latitude': 40.7061738002948, 'longitude': -7...",NaN
16,Steiner Studios,"[15 Washington Ave, Brooklyn, NY 11205]",Brooklyn,4.5,7,"{'latitude': 40.6983157794782, 'longitude': -7...",NaN
17,Ground Glass Motion Picture Company,"[195 Christie St, New York, NY 10002]",New York,5.0,1,"{'latitude': 40.7221489, 'longitude': -73.9923...",NaN
18,Vengo Films,"[8913 4th Ave, Ste 5837, Brooklyn, NY 11209]",Brooklyn,5.0,1,"{'latitude': 40.620018, 'longitude': -74.0292025}",NaN
19,Urban Myth Studio,"[505 Johnson Ave, Brooklyn, NY 11237]",Brooklyn,5.0,4,"{'latitude': 40.708663918903, 'longitude': -73...",NaN
20,Automatic Studios,"[52 Bridge St, Brooklyn, NY 11201]",Brooklyn,4.0,7,"{'latitude': 40.703069, 'longitude': -73.98468}",NaN
21,Gee Media,"[Brooklyn, NY 11225]",Brooklyn,5.0,4,"{'latitude': 40.66363, 'longitude': -73.95541}",NaN
22,Miller/Datri Entertainment,"[600 Fifth Ave, Fl 2, New York, NY 10020]",New York,5.0,4,"{'latitude': 40.758596, 'longitude': -73.9784575}",NaN
23,Film Trade,"[86 Verona St, New York, NY 11231]",New York,5.0,1,"{'latitude': 40.6796212181687, 'longitude': -7...",NaN
24,Hello World Communications,"[118 W 22nd St, Fl 2, New York, NY 10011]",New York,5.0,42,"{'latitude': 40.7425398, 'longitude': -73.9945...",NaN
25,RUX Media,"[50 Harrison St, Hoboken, NJ 07030]",Hoboken,5.0,1,"{'latitude': 40.7372343, 'longitude': -74.042797}",NaN
26,And/With Creative,"[102 Bay Ridge Ave, Ste 2F, Brooklyn, NY 11220]",Brooklyn,5.0,1,"{'latitude': 40.63741, 'longitude': -74.03218}",NaN
27,New York Film Shop,"[437 Washington St, New York, NY 10013]",New York,5.0,3,"{'latitude': 40.7232895, 'longitude': -74.0101...",NaN
28,GUM Studios,"[4508 2nd Ave, Brooklyn, NY 11232]",Brooklyn,5.0,1,"{'latitude': 40.65181, 'longitude': -74.0143}",NaN
29,Cage Free Productions,"[15 Hawthorne St, Ste 3B, Brooklyn, NY 11225]",Brooklyn,5.0,1,"{'latitude': 40.657474, 'longitude': -73.959732}",NaN
30,Starr Street Studios,"[207-A Starr St, Ste 3-1, Brooklyn, NY 11237]",Brooklyn,5.0,8,"{'latitude': 40.705122, 'longitude': -73.923457}",NaN
31,The Edit Center,"[168 7th St, Ste 314, Brooklyn, NY 11215]",Brooklyn,5.0,6,"{'latitude': 40.6728208, 'longitude': -73.9909...",NaN
32,Muve Media,"[36 Waverly Ave, Brooklyn, NY 11205]",Brooklyn,5.0,1,"{'latitude': 40.696788, 'longitude': -73.968833}",NaN
33,MRD Productions,"[500 W 30th St, New York, NY 10001]",New York,5.0,1,"{'latitude': 40.75194, 'longitude': -74.00156}",NaN
34,V-Productions,"[469 7th Ave, New York, NY 10018]",New York,5.0,1,"{'latitude': 40.7519226, 'longitude': -73.9894...",NaN
35,The Cubed Effect,"[New York, NY 11201]",New York,5.0,4,"{'latitude': 40.69347, 'longitude': -73.99052}",NaN
36,Deverge Studio,"[150 W 28th St, Ste 600, New York, NY 10001]",New York,5.0,5,"{'latitude': 40.74676, 'longitude': -73.99282}",NaN
37,Eastern Effects,"[99 9th St, Brooklyn, NY 11215]",Brooklyn,4.5,3,"{'latitude': 40.6734029529525, 'longitude': -7...",NaN
38,The Self Tape Space,"[W 118th St & Manhattan Ave, New York, NY 10026]",New York,5.0,13,"{'latitude': 40.806343, 'longitude': -73.955873}",NaN
39,Tom Ragan Films,"[Brooklyn, NY 11215]",Brooklyn,5.0,2,"{'latitude': 40.66889, 'longitude': -73.9819}",NaN
40,Fine Art Productions,"[1655 Oak Tree Rd, Ste 270, Edison, NJ 08820]",Edison,4.5,19,"{'latitude': 40.5709695115082, 'longitude': -7...",NaN
41,Hello Super Studios,"[Brooklyn, NY 11206]",Brooklyn,5.0,9,"{'latitude': 40.7038917541504, 'longitude': -7...",NaN
42,AbelCine,"[Industry City, 88 35th St, Fl 4, Brooklyn, NY...",Brooklyn,3.5,9,"{'latitude': 40.6564111, 'longitude': -74.0067...",4.0
43,Jersey Filmmaker,"[Jersey City, NJ 07302]",Jersey City,5.0,1,"{'latitude': 40.7218017578125, 'longitude': -7...",NaN
44,Latour de Force Productions,"[New York, NY 10019]",New York,5.0,7,"{'latitude': 40.7645378112793, 'longitude': -7...",NaN
45,Brain Fry Productions,"[2853 Steinway St, 2F, Astoria, NY 11103]",Astoria,5.0,2,"{'latitude': 40.630508, 'longitude': -74.028456}",NaN
46,Silvercup Studios,"[42-22 22nd St, Long Island City, NY 11101]",Long Island City,4.5,12,"{'latitude': 40.751331, 'longitude': -73.943515}",NaN
47,YouTube Space,"[75 9th Ave, New York, NY 10011]",New York,5.0,6,"{'latitude': 40.742581, 'longitude': -74.005434}",NaN
48,Sun Production,"[36-06 30th St, C7, Astoria, NY 11106]",Astoria,5.0,1,"{'latitude': 40.756815, 'longitude': -73.930988}",NaN
49,Broadway Stages,"[359 Kingsland Ave, Greenpoint, NY 11222]",Greenpoint,4.0,1,"{'latitude': 40.7289565103425, 'longitude': -7...",NaN

In [206]:
called_1k.tail()

,Name,Address,City,Rating,Review Count,Coordinates,Price
45,Brain Fry Productions,"[2853 Steinway St, 2F, Astoria, NY 11103]",Astoria,5.0,2,"{'latitude': 40.630508, 'longitude': -74.028456}",NaN
46,Silvercup Studios,"[42-22 22nd St, Long Island City, NY 11101]",Long Island City,4.5,12,"{'latitude': 40.751331, 'longitude': -73.943515}",NaN
47,YouTube Space,"[75 9th Ave, New York, NY 10011]",New York,5.0,6,"{'latitude': 40.742581, 'longitude': -74.005434}",NaN
48,Sun Production,"[36-06 30th St, C7, Astoria, NY 11106]",Astoria,5.0,1,"{'latitude': 40.756815, 'longitude': -73.930988}",NaN
49,Broadway Stages,"[359 Kingsland Ave, Greenpoint, NY 11222]",Greenpoint,4.0,1,"{'latitude': 40.7289565103425, 'longitude': -7...",NaN

In [163]:
test_parsed = parse_data(results['businesses'])
test_parsed
test_d = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
test_d.append(parsed)

,0,1,2,3,4,5,6,Address,City,Coordinates,Name,Price,Rating,Review Count
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1166 Manhattan Ave, Ste 201, Brooklyn, NY 11222]",Brooklyn,"{'latitude': 40.7382584, 'longitude': -73.9549...",DiJiFi,2.0,4.5,165.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[42 West St, Ste 301, Brooklyn, NY 11222]",Brooklyn,"{'latitude': 40.7280427, 'longitude': -73.9588...",590films,NaN,5.0,4.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[13 Lexington Ave, Brooklyn, NY 11238]",Brooklyn,"{'latitude': 40.6866128, 'longitude': -73.9616...",Shell's Loft Brooklyn,NaN,5.0,2.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[193 Marcus Garvey Blvd, Brooklyn, NY 11221]",Brooklyn,"{'latitude': 40.691765, 'longitude': -73.939434}",Mind of Who Productions,NaN,4.5,2.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Brooklyn, NY 11231]",Brooklyn,"{'latitude': 40.6772802, 'longitude': -74.0094...",Kaleidoscope Pictures,NaN,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,Brain Fry Productions,"[2853 Steinway St, 2F, Astoria, NY 11103]",Astoria,5.0,2.0,"{'latitude': 40.630508, 'longitude': -74.028456}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Silvercup Studios,"[42-22 22nd St, Long Island City, NY 11101]",Long Island City,4.5,12.0,"{'latitude': 40.751331, 'longitude': -73.943515}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,YouTube Space,"[75 9th Ave, New York, NY 10011]",New York,5.0,6.0,"{'latitude': 40.742581, 'longitude': -74.005434}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Sun Production,"[36-06 30th St, C7, Astoria, NY 11106]",Astoria,5.0,1.0,"{'latitude': 40.756815, 'longitude': -73.930988}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Broadway Stages,"[359 Kingsland Ave, Greenpoint, NY 11222]",Greenpoint,4.0,1.0,"{'latitude': 40.7289565103425, 'longitude': -7...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [336]:
len(biz_list)

296

In [337]:
num
# len(biz_list)

298

In [341]:
df.iloc[198:202]

,Name,Address,City,Rating,Review Count,Coordinates,Price
198,Musiclab NYC,"[Elmont, NY 11003]",Elmont,5.0,1,"{'latitude': 40.6943581912167, 'longitude': -7...",NaN
199,Crystal Lake Pictures,"[101 Crawfords Corner Rd, Ste 4-101R, Holmdel,...",Holmdel,3.0,2,"{'latitude': 40.3650877, 'longitude': -74.167457}",NaN
200,Dancejock Productions,"[40 Burt Dr, Ste 1, Deer Park, NY 11729]",Deer Park,4.5,12,"{'latitude': 40.758861, 'longitude': -73.305488}",NaN
201,rjephoto,"[basking ridge, NJ 07920]",basking ridge,5.0,2,"{'latitude': 40.7064399719238, 'longitude': -7...",NaN

In [288]:
url_params

{'term': 'Film+Production',
 'location': 'Brooklyn',
 'categories': 'Video/Film',
 'limit': 50,
 'offset': 0}

In [246]:
"""
GOD FUCKING DAMMIT
"""
df.iloc[48:52]

,Name,Address,City,Rating,Review Count,Coordinates,Price
48,Steve Palmer Films,"[New York, NY 11215]",New York,5.0,1,"{'latitude': 40.66874, 'longitude': -73.98181}",NaN
49,Prosper Digital TV,"[33 35th St, Fl 5. Ste 523, Brooklyn, NY 11232]",Brooklyn,5.0,6,"{'latitude': 40.65722, 'longitude': -74.00735}",NaN
50,DiJiFi,"[1166 Manhattan Ave, Ste 201, Brooklyn, NY 11222]",Brooklyn,4.5,165,"{'latitude': 40.7382584, 'longitude': -73.9549...",2.0
51,590films,"[42 West St, Ste 301, Brooklyn, NY 11222]",Brooklyn,5.0,4,"{'latitude': 40.7280427, 'longitude': -73.9588...",NaN

In [241]:
# len(biz_list) ## 1000

TypeError: unhashable type: 'list'

In [228]:
yelp_call(headers, url_params)

{'error': {'code': 'VALIDATION_ERROR',
  'description': 'Too many results requested, limit+offset must be <= 1000.'}}

In [231]:
len(biz_list)

0

In [ ]:
def get_restaurants(city, offset):
    """
    THIS IS ANOTHER APPROACH FROM GITHUB
    Make API request to Yelp to get restaurants for a city, and offset the results by an amount.

    Note that Yelp only returns 20 results each time, which is why we need to offset if we want
    the next Nth results.
    """

      """ WE HAVE THIS """
#     # Read Yelp API keys
#     with io.open('config_secret.json') as cred:
#         creds = json.load(cred)
#         auth = Oauth1Authenticator(**creds)
#         client = Client(auth)

    # Set search parameters for Yelp API request
    # Set term as restaurant to get restaurants back as the results
    # Also pass in offset, so Yelp knows how much to offset by

      """ WE HAVE THIS TOO """
    #     params = {
#         'term': 'restaurant',
#         'offset': offset
#     }

    # Make Yelp API call and return the API response
    return client.search(city, **params)

In [113]:
results = yelp_call(headers, url_params)
parsed = parse_data(results['businesses'])
len(parsed)

50

In [ ]:
 """ 
 THIS IS PART 2 OF ANOTHER APPROACH FROM GITHUB
 Get all restaurants for a city from Yelp and load restaurants into database.
 """

    # Get city id, as city id is a required parameter when adding a restaurant to the database
    city_id = get_city_id(city)

    # Start offset at 0 to return the first 20 results from Yelp API request
    offset = 0
    response = get_restaurants(city, offset)

    # Get total number of restaurants for this city
    total_results = response.total 
    """ 
    ^ AHA, THIS IS WHAT WE NEED FOR num IN OUR WHILE LOOP!
    
    JAKE POINTED TO THIS BUT INPUT TOTAL OF DATA VARIABLE, NOT JSON TOTAL
    
    WOULD BE EQUIVALENT TO LEN(PARSED) RIGHT AFTER DEFINING PARSED IN OUR WHILE LOOP
    
    PROBABLY DO NOT NEED IT
    ACTUALLY ENSURING THAT WE ARE NOT CALLING MORE THAN TOTAL POSSIBLE RESULTS 
    (AS JAKE WAS DOING WITH DATA['TOTAL'] IS SMART
    """

    # Offset by 20 each time to get all restaurants and load each restaurant into the database
    while offset < total_results:

        #CODE BELOW is essentially our PARSE_DATA() function
        for business in response.businesses:
            restaurant = Restaurant(city_id=city_id,
                                    name=business.name,
                                    address=" ".join(business.location.display_address),
                                    phone=business.display_phone,
                                    image_url=business.image_url,
                                    latitude=business.location.coordinate.latitude,
                                    longitude=business.location.coordinate.longitude)

            # Add each restaurant to the db
        #THIS IS WHAT WE NEED TO DO CORRECTLY
            db.session.add(restaurant)

        offset += 20

        response = get_restaurants(city, offset)

In [103]:
pd.DataFrame(parsed[0:3], columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])

,Name,Address,City,Rating,Review Count,Coordinates,Price
0,DiJiFi,"[1166 Manhattan Ave, Ste 201, Brooklyn, NY 11222]",Brooklyn,4.5,165,"{'latitude': 40.7382584, 'longitude': -73.9549...",2.0
1,590films,"[42 West St, Ste 301, Brooklyn, NY 11222]",Brooklyn,5.0,4,"{'latitude': 40.7280427, 'longitude': -73.9588...",NaN
2,Shell's Loft Brooklyn,"[13 Lexington Ave, Brooklyn, NY 11238]",Brooklyn,5.0,2,"{'latitude': 40.6866128, 'longitude': -73.9616...",NaN

In [203]:
def call_1000():
    """ MIKE NOTES: 
    12/13 â€” I believe num should be referring to the number of 
    results that are in our dataframe or dict.
    
    12/14 â€” Might not be a bad idea to loop through offset BEFORE writing to a csv file.
    This could be done by offsetting, adding new to a dict, then writing to a csv file
    *afterwards outside of our while-loop*. 
    ***Persistent opening/writing to csv is messy AF***
    
    df might need to be defined BEFORE while-loop, then APPENDED or CONCAT within while-loop.
    """
    current_offset = 0
    url_params['offset'] = current_offset
    results = yelp_call(headers, url_params)
    parsed = parse_data(results['businesses'])
    num = results['total']
#     total_called = len(parsed)
    df = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
    while current_offset < (num+50) and current_offset < 1000:     
#         concat or append df here
#             current_offset += 50
#             url_params['offset'] = current_offset
#             results = yelp_call(headers, url_params)
#             parsed = parse_data(results['businesses'])
            
            df2 = pd.DataFrame(parsed, columns=['Name', 'Address','City', 'Rating','Review Count','Coordinates','Price'])
            df.append(df2)
        current_offset += 50
        url_params['offset'] = current_offset
        results = yelp_call(headers, url_params)
        parsed = parse_data(results['businesses'])
    return df


#     pd.concat([df, df_2])

# df_save(csv_filepath, df)
# pd.read_csv(csv_filepath)
# Jake's suggestion, create workaround that checks to see â€”â€” 
#if ['businesses'] in data.keys():